### ISSUE TITLE
Error on Pollard_p_1 attack

### ISSUE THREAD

**Issue by deltaclock** [Ganapati/RsaCtfTool#10]
[*] Performing Pollard_p_1 attack.
Traceback (most recent call last):
  File "/home/kali/pentest/tools/RsaCtfTool/RsaCtfTool.py", line 488, in <module>
    attackobj.attack()
  File "/home/kali/pentest/tools/RsaCtfTool/RsaCtfTool.py", line 391, in attack
    getattr(self, attack.__name__)()
  File "/home/kali/pentest/tools/RsaCtfTool/RsaCtfTool.py", line 369, in Pollard_p_1
    self.pub_key.p, self.pub_key.q = pollard_P_1(self.pub_key.n)
TypeError: 'int' object is not iterable

**Comment by maxitis92** [comment]
i have the same problem

**Comment by Nakazona** [comment]
Same

**Comment by helmhammerhand** [comment]
I had the same issue. It is fixable by changing line 49 in p_1.py from 'return 0'  to 'return 0,None'

**Comment by maxitis92** [comment]
i have other problem.

./RsaCtfTool.py --publickey ./key.pub --uncipher ./flag.enc 

[*] Warning: Modulus too large for SIQS attack module
[-] Sorry, cracking failed

**Comment by pr0mming** [comment]
Interestingly this problem does not arise in previous versions like this fork -> https://github.com/sourcekris/RsaCtfTool
