### ISSUE TITLE
cube_root.py"  line 26 non-hexadecimal number found in fromhex() arg at position 47

### ISSUE THREAD

**Issue by wgf4242** [Ganapati/RsaCtfTool#104]
Run code below, then got an error.
```
python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
```

```
[*] Testing key /tmp/tmp60pindkb.
[*] Performing siqs attack on /tmp/tmp60pindkb.
[!] Yafu SIQS is not working.
[*] Performing comfact_cn attack on /tmp/tmp60pindkb.
[*] Performing cube_root attack on /tmp/tmp60pindkb.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 258, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/Downloads/RsaCtfTool/lib/rsa_attack.py", line 193, in attack_single_key
    self, self.publickey, self.cipher
  File "/home/kali/Downloads/RsaCtfTool/attacks/single_key/cube_root.py", line 26, in attack
    plain.append(bytes.fromhex(m))
ValueError: non-hexadecimal number found in fromhex() arg at position 47


```

**Comment by Ganapati** [comment]
Can you give me more informations (where this example is from and full details) ?

**Comment by wgf4242** [comment]
I ran this in Kali-Linux-2020.1-vmware-amd64.
```
kali@kali:~/Downloads/RsaCtfTool$ python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839

[*] Testing key /tmp/tmpld9jht8d.
[*] Performing siqs attack on /tmp/tmpld9jht8d.
[!] Yafu SIQS is not working.
[*] Performing comfact_cn attack on /tmp/tmpld9jht8d.
[*] Performing cube_root attack on /tmp/tmpld9jht8d.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 258, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/Downloads/RsaCtfTool/lib/rsa_attack.py", line 193, in attack_single_key
    self, self.publickey, self.cipher
  File "/home/kali/Downloads/RsaCtfTool/attacks/single_key/cube_root.py", line 26, in attack
    plain.append(bytes.fromhex(m))
ValueError: non-hexadecimal number found in fromhex() arg at position 47
kali@kali:~/Downloads/RsaCtfTool$ 

```

**Comment by Ganapati** [comment]
fixed by new commit

**Comment by donald1990** [comment]
> fixed by new commit
I ran it in Kali-Linux-2020.1-vmware-amd64 and got an error.
`root@Donald:~/桌面/RsaCtfTool# python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmphqkjy9gi.
[*] Performing pollard_p_1 attack on /tmp/tmphqkjy9gi.
[*] Performing comfact_cn attack on /tmp/tmphqkjy9gi.
[*] Performing smallfraction attack on /tmp/tmphqkjy9gi.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing partial_q attack on /tmp/tmphqkjy9gi.
[*] Performing ecm attack on /tmp/tmphqkjy9gi.
[*] ECM Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing qicheng attack on /tmp/tmphqkjy9gi.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing londahl attack on /tmp/tmphqkjy9gi.
[*] Performing cube_root attack on /tmp/tmphqkjy9gi.
[*] Performing pastctfprimes attack on /tmp/tmphqkjy9gi.
[*] Performing boneh_durfee attack on /tmp/tmphqkjy9gi.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing wiener attack on /tmp/tmphqkjy9gi.
[*] Performing ecm2 attack on /tmp/tmphqkjy9gi.
[*] ECM2 Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing noveltyprimes attack on /tmp/tmphqkjy9gi.
[*] Performing primefac attack on /tmp/tmphqkjy9gi.
[*] Performing fermat attack on /tmp/tmphqkjy9gi.
[*] Performing roca attack on /tmp/tmphqkjy9gi.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing siqs attack on /tmp/tmphqkjy9gi.
[!] Yafu SIQS is not working.
[*] Performing factordb attack on /tmp/tmphqkjy9gi.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 262, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/root/桌面/RsaCtfTool/lib/rsa_attack.py", line 192, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/root/桌面/RsaCtfTool/attacks/single_key/factordb.py", line 85, in attack
    priv_key = PrivateKey(
  File "/root/桌面/RsaCtfTool/lib/keys_wrapper.py", line 105, in __init__
    self.key = RSA.construct((self.n, self.e, self.d, self.p, self.q))
  File "/usr/local/lib/python3.8/dist-packages/Crypto/PublicKey/RSA.py", line 569, in construct
    u = p.inverse(q)
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Math/_IntegerGMP.py", line 658, in inverse
    result.inplace_inverse(modulus)
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Math/_IntegerGMP.py", line 653, in inplace_inverse
    raise ValueError("No inverse value can be computed")
ValueError: No inverse value can be computed
`

**Comment by Ganapati** [comment]
On my setup : 
```
/m/v/p/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839 --attack cube_root
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmpzh1j4xow.
[*] Performing cube_root attack on /tmp/tmpzh1j4xow.

Results for /tmp/tmpzh1j4xow:

Unciphered data :
HEX : 0x090fb2dd995ca954d68f4014e84ca34908d76761020856cd
INT (big endian) : 222182994028263518461586693429023225808902992832984798925
INT (little endian) : 5034825534206713949867013581663155336648182093090168901385
STR : b'\t\x0f\xb2\xdd\x99\\\xa9T\xd6\x8f@\x14\xe8L\xa3I\x08\xd7ga\x02\x08V\xcd'
```

Do you use the latest version?

**Comment by donald1990** [comment]
> On my setup :
> 
> ```
> /m/v/p/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839 --attack cube_root
> private argument is not set, the private key will not be displayed, even if recovered.
> 
> [*] Testing key /tmp/tmpzh1j4xow.
> [*] Performing cube_root attack on /tmp/tmpzh1j4xow.
> 
> Results for /tmp/tmpzh1j4xow:
> 
> Unciphered data :
> HEX : 0x090fb2dd995ca954d68f4014e84ca34908d76761020856cd
> INT (big endian) : 222182994028263518461586693429023225808902992832984798925
> INT (little endian) : 5034825534206713949867013581663155336648182093090168901385
> STR : b'\t\x0f\xb2\xdd\x99\\\xa9T\xd6\x8f@\x14\xe8L\xa3I\x08\xd7ga\x02\x08V\xcd'
> ```
> 
> Do you use the latest version?

Yes, I use the latest version.

**Comment by donald1990** [comment]
> python3 ./RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839 --attack cube_root

If I ran with  --attack cube_root can run successfully.
```
 root@Donald:~/桌面/RsaCtfTool# python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmpnurmc8j2.
[*] Performing pollard_p_1 attack on /tmp/tmpnurmc8j2.
[*] Performing comfact_cn attack on /tmp/tmpnurmc8j2.
[*] Performing smallfraction attack on /tmp/tmpnurmc8j2.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing partial_q attack on /tmp/tmpnurmc8j2.
[*] Performing ecm attack on /tmp/tmpnurmc8j2.
[*] ECM Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing qicheng attack on /tmp/tmpnurmc8j2.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing londahl attack on /tmp/tmpnurmc8j2.
[*] Performing cube_root attack on /tmp/tmpnurmc8j2.
[*] Performing pastctfprimes attack on /tmp/tmpnurmc8j2.
[*] Performing boneh_durfee attack on /tmp/tmpnurmc8j2.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing wiener attack on /tmp/tmpnurmc8j2.
[*] Performing ecm2 attack on /tmp/tmpnurmc8j2.
[*] ECM2 Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing noveltyprimes attack on /tmp/tmpnurmc8j2.
[*] Performing primefac attack on /tmp/tmpnurmc8j2.
[*] Performing fermat attack on /tmp/tmpnurmc8j2.
[*] Performing roca attack on /tmp/tmpnurmc8j2.
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/usr/bin/SageMath/
New SAGE_ROOT=/usr/bin/SageMath
[*] Performing siqs attack on /tmp/tmpnurmc8j2.
[!] Yafu SIQS is not working.
[*] Performing factordb attack on /tmp/tmpnurmc8j2.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 262, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/root/桌面/RsaCtfTool/lib/rsa_attack.py", line 192, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/root/桌面/RsaCtfTool/attacks/single_key/factordb.py", line 85, in attack
    priv_key = PrivateKey(
  File "/root/桌面/RsaCtfTool/lib/keys_wrapper.py", line 105, in __init__
    self.key = RSA.construct((self.n, self.e, self.d, self.p, self.q))
  File "/usr/local/lib/python3.8/dist-packages/Crypto/PublicKey/RSA.py", line 569, in construct
    u = p.inverse(q)
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Math/_IntegerGMP.py", line 658, in inverse
    result.inplace_inverse(modulus)
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Math/_IntegerGMP.py", line 653, in inplace_inverse
    raise ValueError("No inverse value can be computed")
ValueError: No inverse value can be computed
^CProcess Process-5:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
Process Process-1:
Process Process-6:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_fermat.py", line 10, in fermat
    w = x ** 2 - n - y ** 2
KeyboardInterrupt
Process Process-2:
Traceback (most recent call last):
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_williams_pp1.py", line 36, in williams_pp1
    v = mlucas(v, p, n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_williams_pp1.py", line 14, in mlucas
    else ((v1 * v2 - v) % n, (v2 ** 2 - 2) % n)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_pollard_rho_brent.py", line 23, in pollardRho_brent
    q = q * abs(x - y) % n
KeyboardInterrupt
Process Process-4:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_pollard_pm1.py", line 26, in pollard_pm1
    q, p = pow(q, p, n), six.next(pg)
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_mpqs.py", line 122, in mpqs
    k += p
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/桌面/RsaCtfTool/attacks/single_key/primefac.py", line 50, in factory
    g = method(n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_ecm.py", line 98, in ecm
    Q = _ecmul(p, Q, C, n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_ecm.py", line 40, in _ecmul
    q, r = _ecdub(q, A, n), _ecadd(q, r, p, n)
  File "/root/桌面/RsaCtfTool/_primefac/_factor_algo/_ecm.py", line 20, in _ecdub
    return (t1 * t2 * 4 * Ad % n, (4 * Ad * t2 + t * An) * t % n)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
root@Donald:~/桌面/RsaCtfTool# python3 ./RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839 --attack cube_root
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp1etbb2l7.
[*] Performing cube_root attack on /tmp/tmp1etbb2l7.

Results for /tmp/tmp1etbb2l7:

Unciphered data :
HEX : 0x090fb2dd995ca954d68f4014e84ca34908d76761020856cd
INT (big endian) : 222182994028263518461586693429023225808902992832984798925
INT (little endian) : 5034825534206713949867013581663155336648182093090168901385
STR : b'\t\x0f\xb2\xdd\x99\\\xa9T\xd6\x8f@\x14\xe8L\xa3I\x08\xd7ga\x02\x08V\xcd'
```

**Comment by kolayne** [comment]
I am running the latest git version and reproduce none of the problems. My outputs are:
```
nikolay@Linux-coder:/tmp/RsaCtfTool$ python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmpcjizess4.
Can't load ecm because sage is not installed
Can't load roca because sage is not installed
Can't load qicheng because sage is not installed
Can't load boneh_durfee because sage is not installed
Can't load ecm2 because sage is not installed
Can't load smallfraction because sage is not installed
[*] Performing pollard_p_1 attack on /tmp/tmpcjizess4.
[*] Performing mersenne_primes attack on /tmp/tmpcjizess4.
[*] Performing primefac attack on /tmp/tmpcjizess4.
[*] Performing factordb attack on /tmp/tmpcjizess4.

Results for /tmp/tmpcjizess4:

Unciphered data :
HEX : 0x0b5362cad369054556d43ba5ba1c54490a37d7dd0b465716abff5743c822ca3e7699b105fef8a21793f76618f64a0fa8bdc4953f46ebb52544697dc555e3f875cfa4daf250ecef
INT (big endian) : 42742865115217691609371560122571256344946343182365982696069625281748364673764979961922038997650877453472359239480913245234731901768357544815825003043302680811332663569647
INT (little endian) : 905460802659434276736964650798183159691607791568829975035943695059488064477458172915596868445249833396350684345289887210485738277836014880002695067064007566119652500329227
STR : b'\x0bSb\xca\xd3i\x05EV\xd4;\xa5\xba\x1cTI\n7\xd7\xdd\x0bFW\x16\xab\xffWC\xc8"\xca>v\x99\xb1\x05\xfe\xf8\xa2\x17\x93\xf7f\x18\xf6J\x0f\xa8\xbd\xc4\x95?F\xeb\xb5%Di}\xc5U\xe3\xf8u\xcf\xa4\xda\xf2P\xec\xef'
```
and
```
nikolay@Linux-coder:/tmp/RsaCtfTool$ python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp4td2s83l.
Can't load ecm because sage is not installed
Can't load roca because sage is not installed
Can't load qicheng because sage is not installed
Can't load boneh_durfee because sage is not installed
Can't load ecm2 because sage is not installed
Can't load smallfraction because sage is not installed
[*] Performing pollard_p_1 attack on /tmp/tmp4td2s83l.
[*] Performing mersenne_primes attack on /tmp/tmp4td2s83l.
[*] Performing primefac attack on /tmp/tmp4td2s83l.
[*] Performing factordb attack on /tmp/tmp4td2s83l.

Results for /tmp/tmp4td2s83l:

Unciphered data :
HEX : 0x03ad4b3d9f19d7786a22bef1af8f74fe6b817d892374e1ac374fdc4f7b165fabbc300631d7e6f4e851a79ec584886ec063959535070fef9ffca30a2e53355155a34d00d10ed650
INT (big endian) : 13876593138094452059004304404590537536134711843572464714655869351369588200023956370835023279069736235404781490408558124944485217764041721131417706227620348051841784665680
INT (little endian) : 305072643919490185171690782389721980542475252800842308002731183929315841515292245199894030715332329968442627703524845727998106672801721482599383844804017165016029240995075
STR : b'\x03\xadK=\x9f\x19\xd7xj"\xbe\xf1\xaf\x8ft\xfek\x81}\x89#t\xe1\xac7O\xdcO{\x16_\xab\xbc0\x061\xd7\xe6\xf4\xe8Q\xa7\x9e\xc5\x84\x88n\xc0c\x95\x955\x07\x0f\xef\x9f\xfc\xa3\n.S5QU\xa3M\x00\xd1\x0e\xd6P'
```
(both the processes didn't terminate, if it's important)

Should the issue be closed?

**Comment by donald1990** [comment]
> I am running the latest git version and reproduce none of the problems. My outputs are:
> 
> ```
> nikolay@Linux-coder:/tmp/RsaCtfTool$ python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
> private argument is not set, the private key will not be displayed, even if recovered.
> 
> [*] Testing key /tmp/tmpcjizess4.
> Can't load ecm because sage is not installed
> Can't load roca because sage is not installed
> Can't load qicheng because sage is not installed
> Can't load boneh_durfee because sage is not installed
> Can't load ecm2 because sage is not installed
> Can't load smallfraction because sage is not installed
> [*] Performing pollard_p_1 attack on /tmp/tmpcjizess4.
> [*] Performing mersenne_primes attack on /tmp/tmpcjizess4.
> [*] Performing primefac attack on /tmp/tmpcjizess4.
> [*] Performing factordb attack on /tmp/tmpcjizess4.
> 
> Results for /tmp/tmpcjizess4:
> 
> Unciphered data :
> HEX : 0x0b5362cad369054556d43ba5ba1c54490a37d7dd0b465716abff5743c822ca3e7699b105fef8a21793f76618f64a0fa8bdc4953f46ebb52544697dc555e3f875cfa4daf250ecef
> INT (big endian) : 42742865115217691609371560122571256344946343182365982696069625281748364673764979961922038997650877453472359239480913245234731901768357544815825003043302680811332663569647
> INT (little endian) : 905460802659434276736964650798183159691607791568829975035943695059488064477458172915596868445249833396350684345289887210485738277836014880002695067064007566119652500329227
> STR : b'\x0bSb\xca\xd3i\x05EV\xd4;\xa5\xba\x1cTI\n7\xd7\xdd\x0bFW\x16\xab\xffWC\xc8"\xca>v\x99\xb1\x05\xfe\xf8\xa2\x17\x93\xf7f\x18\xf6J\x0f\xa8\xbd\xc4\x95?F\xeb\xb5%Di}\xc5U\xe3\xf8u\xcf\xa4\xda\xf2P\xec\xef'
> ```
> 
> and
> 
> ```
> nikolay@Linux-coder:/tmp/RsaCtfTool$ python3 RsaCtfTool.py -n 47966708183289639962501363163761864399454241691014467172805658518368423135168025285144721028476297179341434450931955275325060173656301959484440112740411109153032840150659 -e 3 --uncipher 10968126341413081941567552025256642365567988931403833266852196599058668508079150528128483441934584299102782386592369069626088211004467782012298322278772376088171342152839
> private argument is not set, the private key will not be displayed, even if recovered.
> 
> [*] Testing key /tmp/tmp4td2s83l.
> Can't load ecm because sage is not installed
> Can't load roca because sage is not installed
> Can't load qicheng because sage is not installed
> Can't load boneh_durfee because sage is not installed
> Can't load ecm2 because sage is not installed
> Can't load smallfraction because sage is not installed
> [*] Performing pollard_p_1 attack on /tmp/tmp4td2s83l.
> [*] Performing mersenne_primes attack on /tmp/tmp4td2s83l.
> [*] Performing primefac attack on /tmp/tmp4td2s83l.
> [*] Performing factordb attack on /tmp/tmp4td2s83l.
> 
> Results for /tmp/tmp4td2s83l:
> 
> Unciphered data :
> HEX : 0x03ad4b3d9f19d7786a22bef1af8f74fe6b817d892374e1ac374fdc4f7b165fabbc300631d7e6f4e851a79ec584886ec063959535070fef9ffca30a2e53355155a34d00d10ed650
> INT (big endian) : 13876593138094452059004304404590537536134711843572464714655869351369588200023956370835023279069736235404781490408558124944485217764041721131417706227620348051841784665680
> INT (little endian) : 305072643919490185171690782389721980542475252800842308002731183929315841515292245199894030715332329968442627703524845727998106672801721482599383844804017165016029240995075
> STR : b'\x03\xadK=\x9f\x19\xd7xj"\xbe\xf1\xaf\x8ft\xfek\x81}\x89#t\xe1\xac7O\xdcO{\x16_\xab\xbc0\x061\xd7\xe6\xf4\xe8Q\xa7\x9e\xc5\x84\x88n\xc0c\x95\x955\x07\x0f\xef\x9f\xfc\xa3\n.S5QU\xa3M\x00\xd1\x0e\xd6P'
> ```
> 
> (both the processes didn't terminate, if it's important)
> 
> Should the issue be closed?

I have this problem yet. My python3 version is 3.8.2.
