### ISSUE TITLE
NameError: name 'unciphers' is not defined

### ISSUE THREAD

**Issue by woaisthisgit** [Ganapati/RsaCtfTool#105]
Run the below code
python3 RsaCtfTool.py -p 88761620475672281797897005732643499821690688597370440945258776182910533850401433150065043871978311565287949564292158396906865512113015114468175188982916489347656271125993359554057983487741599275948833820107889167078943493772101668339096372868672343763810610724807588466294391846588859523658456534735572626377 -n 5215102981058174620100754813213017625443626121109099133656454487932754235228856710661075956048331662593471061936196995326042367228980357932444477256496372200491821105922086202549125972429240337409176104237690646206864286971669895986447543904638596421264915837230690039800948447210554706127145724519079487023930504508462885777797916915752532472831523596571484341342780877665593787078959178539369282442522815729401991936772080063808078804309866694041173404657777517753433918322041736500126265865045225739241983004392226366771900174432875800986183772576663590650132115754645829772406067103501861326445534174181231077263 -e 5 --uncipher 4131551751757367507477907831392714046331558150814204269429896384648692788012491946122498603090480872693652158373495305395336029559809450357806318606432425689167369413561930000927362737566359174227097877780143294233282859699795909710240766180303730075227786852285437540114279424843216893481747607054883124698955194618553340156634102058475713383885677287466808165857519348882039449681212885205882337152158140601371625025994299806541918266324416251998280113757829441820324540236159226753097699280516887119083595384934720138675180508993660508783443152795860498444053762822622587170995227091549141326817450712163117582988

Get following error:
Traceback (most recent call last):
  File "RsaCtfTool.py", line 206, in <module>
    unciphers.append(priv_key.decrypt(args.u))
NameError: name 'unciphers' is not defined

I looked in the code, unciphers is defined.

**Comment by Ganapati** [comment]
Fixed in latest commit, 
enjoy your "rtcp{****************}" flag !

**Comment by woaisthisgit** [comment]
haha thanks :)
