### ISSUE TITLE
Problem with this tool

### ISSUE THREAD

**Issue by mzanrosso** [Ganapati/RsaCtfTool#106]
hi,
i'm trying to do this

python3 RsaCtfTool.py -n 245841236512478852752909734912575581815967630033049838269083 -e 1 --uncipher 9327565722767258308650643213344542404592011161659991421

but with this error:
Traceback (most recent call last):
  File "RsaCtfTool.py", line 182, in <module>
    tmpfd.write(RSA.construct((args.n, args.e)).publickey().exportKey())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 579, in construct
    raise ValueError("Invalid RSA public exponent")
ValueError: Invalid RSA public exponent

**Comment by Ganapati** [comment]
When RsaCtfTool try to construct a Private key, libCryptodom crash because (according to documentation) "The public exponent e must be odd and larger than 1.".
I'm working on this for the uncipher case.

**Comment by mzanrosso** [comment]
Thanks!

**Comment by mzanrosso** [comment]
It doesn’t work yet, even with the last commit

**Comment by Ganapati** [comment]
Can you give me the full output ?

**Comment by mzanrosso** [comment]
Mac5:RsaCtfTool marcozanrosso$ git pull
Already up to date.
Mac5:RsaCtfTool marcozanrosso$ git fetch
Mac5:RsaCtfTool marcozanrosso$ python3 RsaCtfTool.py -n 245841236512478852752909734912575581815967630033049838269083 -e 1 --uncipher 9327565722767258308650643213344542404592011161659991421
Traceback (most recent call last):
  File "RsaCtfTool.py", line 182, in <module>
    tmpfd.write(RSA.construct((args.n, args.e)).publickey().exportKey())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 579, in construct
    raise ValueError("Invalid RSA public exponent")
ValueError: Invalid RSA public exponent
Mac5:RsaCtfTool marcozanrosso$

**Comment by mzanrosso** [comment]
`Mac5:RsaCtfTool marcozanrosso$ git log
commit f54e80f4264381d9466ab6291210aa2b66ca7ded (HEAD -> master, origin/master, origin/HEAD)
Author: Ganapati <ganapati@foobar.baz>
Date:   Mon Apr 27 10:14:59 2020 +0200

    Fix uncipher with p and n`

**Comment by Ganapati** [comment]
I'm on the same version...
It seems to be a pycryptodome difference bug.. I'm looking for a fix.

**Comment by Ganapati** [comment]
Try removing pycryptodome
```

**Comment by mzanrosso** [comment]
ac5:RsaCtfTool marcozanrosso$ sudo pip3 uninstall pycryptodome
Password:
The directory '/Users/marcozanrosso/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling pycryptodome-3.9.7:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Crypto/*
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycryptodome-3.9.7.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled pycryptodome-3.9.7
Mac5:RsaCtfTool marcozanrosso$ python3 ./RsaCtfTool.py -n 245841236512478852752909734912575581815967630033049838269083 -e 1 --uncipher 9327565722767258308650643213344542404592011161659991421
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
Mac5:RsaCtfTool marcozanrosso$

**Comment by Ganapati** [comment]
You don't have pycrypto installed I think.
pycrypto and pycryptodome don't work very well together.

**Comment by mzanrosso** [comment]
`Mac5:RsaCtfTool marcozanrosso$ sudo pip3 install pycrypto
The directory '/Users/marcozanrosso/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/marcozanrosso/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pycrypto in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2.6.1)
You are using pip version 19.0.3, however version 20.1b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Mac5:RsaCtfTool marcozanrosso$ python3 ./RsaCtfTool.py -n 245841236512478852752909734912575581815967630033049838269083 -e 1 --uncipher 9327565722767258308650643213344542404592011161659991421
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
Mac5:RsaCtfTool marcozanrosso$ `

**Comment by Ganapati** [comment]
look at my setup and diff with your : 
```
>>> pip3 list |grep crypto
asn1crypto                   0.24.0         
cryptography                 2.8            
pycrypto                     2.6.1          
pycryptodomex                3.6.1 
```

**Comment by mzanrosso** [comment]
Mac5:RsaCtfTool marcozanrosso$ pip3 list |grep crypto
asn1crypto    1.3.0     
crypto        1.4.1     
cryptography  2.9.2     
pycrypto      2.6.1     
pycryptodomex 3.9.7

**Comment by Ganapati** [comment]
I've upgraded everything on my setup to match your :
```
asn1crypto                   1.3.0          
crypto                       1.4.1          
cryptography                 2.9.2          
pycrypto                     2.6.1          
pycryptodomex                3.9.7 
```
Still working on my setup.

**Comment by mzanrosso** [comment]
i reinstalled pycrypto and it worked:
Mac5:RsaCtfTool marcozanrosso$ python3 ./RsaCtfTool.py -n 245841236512478852752909734912575581815967630033049838269083 -e 1 --uncipher 9327565722767258308650643213344542404592011161659991421

[*] Testing key /var/folders/15/5frq_21d5wn7gyxdjvzgf9gc0000gn/T/tmpqn_7rero.
Can't load smallfraction because sage is not installed
Can't load ecm because sage is not installed
Can't load boneh_durfee because sage is not installed
Can't load ecm2 because sage is not installed
Can't load qicheng because sage is not installed
[*] Performing wiener attack on /var/folders/15/5frq_21d5wn7gyxdjvzgf9gc0000gn/T/tmpqn_7rero.
[*] Performing pastctfprimes attack on /var/folders/15/5frq_21d5wn7gyxdjvzgf9gc0000gn/T/tmpqn_7rero.
[*] Performing factordb attack on /var/folders/15/5frq_21d5wn7gyxdjvzgf9gc0000gn/T/tmpqn_7rero.

Results for /var/folders/15/5frq_21d5wn7gyxdjvzgf9gc0000gn/T/tmpqn_7rero:

Unciphered data :
b'\x00\x00abctf{b3tter_up_y0ur_e}'

**Comment by mzanrosso** [comment]
how can i resolve 

>  because sage is not installed

>

**Comment by Ganapati** [comment]
Download and install the tarball sagemath : 
https://doc.sagemath.org/html/en/installation/binary.html#linux

**Comment by dextronomous** [comment]
Hi guys, read all in here, i guess.,
Desktop/RsaCtfTool/lib/rsa_attack.py", line 194, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
TypeError: cannot unpack non-iterable NoneType object
how to fix this
