### ISSUE TITLE
sage is not installed

### ISSUE THREAD

**Issue by brother0k** [Ganapati/RsaCtfTool#108]
[*] Testing key key.pub.
Can't load roca because sage is not installed
Can't load smallfraction because sage is not installed
Can't load ecm2 because sage is not installed
Can't load qicheng because sage is not installed
Can't load boneh_durfee because sage is not installed
Can't load ecm because sage is not installed

//sage and sagemath installed
Requirement already satisfied: sage in /home/user/.local/lib/python3.8/site-packages (0.0.0)
Requirement already satisfied: sagemath in /home/user/.local/lib/python3.8/site-packages (1.3.0)
Requirement already satisfied: cython>=0.26 in /usr/lib/python3/dist-packages (from sagemath) (0.29.14)

Where is mistake?

**Comment by Ganapati** [comment]
Do you have sage binary installed with the "sage" command in your PATH ?
Try to run `sage -v` in a terminal to check if your installation is correct.

Once sage will be runnable from your terminal, it will be from RsaCtfTool.

example on my setup : 
```
~ ❯❯❯ sage -v
SageMath version 9.0, Release Date: 2020-01-01
```

**Comment by brother0k** [comment]
> Do you have sage binary installed with the "sage" command in your PATH ?
> Try to run `sage -v` in a terminal to check if your installation is correct.
> 
> Once sage will be runnable from your terminal, it will be from RsaCtfTool.
> 
> example on my setup :
> 
> ```
> ~ ❯❯❯ sage -v
> SageMath version 9.0, Release Date: 2020-01-01
> ```
> 
> You can find binaries on https://www.sagemath.org/download.html

Solved! Thanks a lot.
My mistake i thought need install sage and sagemath only in pip3.
When i installed sagemath in system all fine.

**Comment by fiddystatic** [comment]
Hi, I'm facing the same problem. So you say I install sagemath & then run sage -v on the terminal in RsaCtfTool... and all will be okay?
