### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by maxitis92** [Ganapati/RsaCtfTool#11]
**i write this code  ./RsaCtfTool.py --publickey ./key.pub --uncipher ./flag.enc** 

Traceback (most recent call last):
  File "./RsaCtfTool.py", line 488, in <module>
    attackobj.attack()
  File "./RsaCtfTool.py", line 391, in attack
    getattr(self, attack.__name__)()
  File "./RsaCtfTool.py", line 369, in Pollard_p_1
    self.pub_key.p, self.pub_key.q = pollard_P_1(self.pub_key.n)
TypeError: 'int' object is not iterable

**what is the problem???**

**Comment by deltaclock** [comment]
1. Dont open another issue for the same problem
2. Just use an old version

**Comment by pr0mming** [comment]
As it says @deltaclock use another version, it is possible that with this fork you can find a solution https://github.com/sourcekris/RsaCtfTool

**Comment by Ganapati** [comment]
Fixed some commits before.
