### ISSUE TITLE
Usability suggestion: warn in private key recovered

### ISSUE THREAD

**Issue by kazkansouh** [Ganapati/RsaCtfTool#111]
Hello.

First, thank you for making such a useful tool. I'm still learning it and getting more confidence in its use. However, I do have a suggestion that might be worth considering if its easy to implement.

I was running the tool without the `--private` flag, so it did not display the private key when discovered and kept running other attacks. I.e.

```
./RsaCtfTool.py --publickey somekey.pub
```

I wonder if it would be appropriate to either print a warning at the beginning when running like this  that if the private key is found that it will not be printed without `--private`. Or add a summary line after each attack if the attack was successful?

I appreciate this is described in the help text, and is a fairly minor improvement. But in truth I only realised this after trying other tools and confirming that the public key was vulnerable, so came back to RsaCtfTool to understand why it was not finding the private key.

**Comment by Ganapati** [comment]
Added in commit [d4fd69bd59941b7fddc41782f1bc020581ece732](https://github.com/Ganapati/RsaCtfTool/commit/d4fd69bd59941b7fddc41782f1bc020581ece732).

Thx for the idea !

**Comment by kazkansouh** [comment]
It looks good, thanks for making the change :smile:
