### ISSUE TITLE
The uncipher result is incorrect

### ISSUE THREAD

**Issue by donald1990** [Ganapati/RsaCtfTool#115]
Below is a CTF question:
```
Math is cool! Use the RSA algorithm to decode the secret message, c, p, q, and e are parameters for the RSA algorithm.
p =  9648423029010515676590551740010426534945737639235739800643989352039852507298491399561035009163427050370107570733633350911691280297777160200625281665378483
q =  11874843837980297032092405848653656852760910154543380907650040190704283358909208578251063047732443992230647903887510065547947313543299303261986053486569407
e =  65537
c =  83208298995174604174773590298203639360540024871256126892889661345742403314929861939100492666605647316646576486526217457006376842280869728581726746401583705899941768214138742259689334840735633553053887641847651173776251820293087212885670180367406807406765923638973161375817392737747832762751690104423869019034
Use RSA to find the secret message
```

I run code below
`python3 RsaCtfTool.py -p 9648423029010515676590551740010426534945737639235739800643989352039852507298491399561035009163427050370107570733633350911691280297777160200625281665378483 -q 11874843837980297032092405848653656852760910154543380907650040190704283358909208578251063047732443992230647903887510065547947313543299303261986053486569407 -e 65537 --uncipher 83208298995174604174773590298203639360540024871256126892889661345742403314929861939100492666605647316646576486526217457006376842280869728581726746401583705899941768214138742259689334840735633553053887641847651173776251820293087212885670180367406807406765923638973161375817392737747832762751690104423869019034`
Then I got this:
```
private argument is not set, the private key will not be displayed, even if recovered.

Results for /tmp/tmp5cenq68q:

Unciphered data :
[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x05\x8eC\xd9\xe0\xc2%Y\xc1\x97t']

```
The unchiphererd data is not correct, it should be 5577446633554466577768879988

**Comment by Ganapati** [comment]
did you try --private and then uncipher with openssl ?

**Comment by donald1990** [comment]
> did you try --private and then uncipher with openssl ?

It tried --private, it didn't work.
I used python code below can get the correct unciphererd data.
`# -*- coding:utf8 -*-
# Python 2.7
import gmpy2
p = 9648423029010515676590551740010426534945737639235739800643989352039852507298491399561035009163427050370107570733633350911691280297777160200625281665378483L
q = 11874843837980297032092405848653656852760910154543380907650040190704283358909208578251063047732443992230647903887510065547947313543299303261986053486569407L
e = 65537L
c = 83208298995174604174773590298203639360540024871256126892889661345742403314929861939100492666605647316646576486526217457006376842280869728581726746401583705899941768214138742259689334840735633553053887641847651173776251820293087212885670180367406807406765923638973161375817392737747832762751690104423869019034L
phi = (p - 1) * (q - 1)
# （n, d）
d = long(gmpy2.invert(e, phi))
n = p * q
# c^d mod n
print pow(c, d, n) 
`
Here is the question. I already know p,q,e, how to uncipher data?

**Comment by Ganapati** [comment]
Working on it. It will be the next commit (I don't know when...)

**Comment by rak1507** [comment]
This is because the data is in bytes form when you want it in integer form. This is not a bug, this is just your misunderstanding of how this works.
The unciphered data *is* correct.
You should learn the basics of this stuff before relying on tools. :)

**Comment by donald1990** [comment]
> 
> 
> Working on it. It will be the next commit (I don't know when...)

Thx. Looking forward to the next commit

**Comment by rak1507** [comment]
There's nothing *to* commit, it already works. You're just dumb.

**Comment by donald1990** [comment]
> 
> 
> This is because the data is in bytes form when you want it in integer form. This is not a bug, this is just your misunderstanding of how this works.
> The unciphered data _is_ correct.
> You should learn the basics of this stuff before relying on tools. :)

I know the data is in bytes.But the unciphered data is not correct. 
I already know p,q,e, how to use this tool only to  get uncipher data?

**Comment by rak1507** [comment]
Don't, do it yourself. 
Or use the tool, and then convert from bytes to int.

**Comment by donald1990** [comment]
> 
> 
> Don't, do it yourself.
> Or use the tool, and then convert from bytes to int.

You tell me how the bytes [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x05\x8eC\xd9\xe0\xc2%Y\xc1\x97t']
can convert to 5577446633554466577768879988

**Comment by rak1507** [comment]
Literally google it.

**Comment by RealJammy** [comment]
^ this tbh

**Comment by willwam845** [comment]
I wrote a short python script that does it. 

[script.txt](https://github.com/Ganapati/RsaCtfTool/files/4781269/script.txt)
As Rak said, it only takes a very quick google search to find all of this.

**Comment by woaisthisgit** [comment]
> > Don't, do it yourself.
> > Or use the tool, and then convert from bytes to int.
> 
> You tell me how the bytes [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x05\x8eC\xd9\xe0\xc2%Y\xc1\x97t']
> can convert to 5577446633554466577768879988

python3
int.from_bytes(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x05\x8eC\xd9\xe0\xc2%Y\xc1\x97t', 'big')

**Comment by donald1990** [comment]
Sorry.

**Comment by Ganapati** [comment]
Output has been updated and now display more informations.

**Comment by donald1990** [comment]
> Output has been updated and now display more informations.

Thanks a lot
