### ISSUE TITLE
[Feature request] Add multiprime RSA support

### ISSUE THREAD

**Issue by woaisthisgit** [Ganapati/RsaCtfTool#119]
Please add multiprime rsa support to rsactftool. Recently challenge devs have been trying to come up with ways to outsmart rsactftool, but i want to see them suffer, so please patch this and make rsa challenges easy to solve once more :D

**Comment by RealJammy** [comment]
I can get behind this. Sounds very sensible

**Comment by TheRoadToDawn** [comment]
Too right.

**Comment by willwam845** [comment]
no please i just want to make an un-rsactftoolable challenge :(

**Comment by Ganapati** [comment]
Can you give me the challenge and input data so i'll see what I can do ?

**Comment by woaisthisgit** [comment]
Thanks for taking a look. An example of a challenge like this is "Raspberry" from the recent NahamCon CTF. I'll link a writeup for it below. The given data is

n = 7735208939848985079680614633581782274371148157293352904905313315409418467322726702848189532721490121708517697848255948254656192793679424796954743649810878292688507385952920229483776389922650388739975072587660866986603080986980359219525111589659191172937047869008331982383695605801970189336227832715706317
e = 65537
c = 5300731709583714451062905238531972160518525080858095184581839366680022995297863013911612079520115435945472004626222058696229239285358638047675780769773922795279074074633888720787195549544835291528116093909456225670152733191556650639553906195856979794273349598903501654956482056938935258794217285615471681

and the flag to retrieve is "flag{there_are_a_few_extra_berries_in_this_one}"

**Comment by woaisthisgit** [comment]
Writeup: [https://github.com/W3rni0/NahamCon_CTF_2020#respberry](url)

**Comment by willwam845** [comment]
The actual thing that needs to be added is that the totient needs to be computed differently, as since there are more primes, the totient becomes (p -1) * (q - 1) * (r - 1) etc for the number of primes there are. The rest is all the same, as far as I can tell.

**Comment by rak1507** [comment]
Also a slightly different formula if any primes are repeated.

**Comment by Ganapati** [comment]
New commit !
```
/m/v/p/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py -n 7735208939848985079680614633581782274371148157293352904905313315409418467322726702848189532721490121708517697848255948254656192793679424796954743649810878292688507385952920229483776389922650388739975072587660866986603080986980359219525111589659191172937047869008331982383695605801970189336227832715706317 -e 65537 --uncipher 5300731709583714451062905238531972160518525080858095184581839366680022995297863013911612079520115435945472004626222058696229239285358638047675780769773922795279074074633888720787195549544835291528116093909456225670152733191556650639553906195856979794273349598903501654956482056938935258794217285615471681 --attack factordb
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp_ge1fn3a.
[*] Performing factordb attack on /tmp/tmp_ge1fn3a.

Results for /tmp/tmp_ge1fn3a:

Unciphered data :
HEX : 0x666c61677b74686572655f6172655f615f6665775f65787472615f626572726965735f696e5f746869735f6f6e657d
INT (big endian) : 61579680106173937457634433345225092813964181603778749362992869924724831902075307955237229635560859630160197870973
INT (little endian) : 75391578580162111202920221063631690447270513421817122605705970497321626114698759596260720953692596138083690310758
STR : b'flag{there_are_a_few_extra_berries_in_this_one}'
HEX : 0x025724b6077aa7480ad2c884aadde485be30c76af71d7dd896df9289676c8dbb076a375eb4ecdd545730930190a903e6fbcc352731977d6e35f87bd121c3c5cade0d801a7652ecc0119b288e2ecf0087c10d089ac47a33af6ed49ca6d0683fa95db0fa3dac696d394831511ff6d9fb5bd48dfe3e8ed5512e45d2e3c8a605d0
INT (big endian) : 6419873127662619680714838865739309153688782325037007547209115542061222162934468963617949863332495171679236002600892230252612179074388694976283043809957835908550068422935356542280737270608978985775995469487618392347348666933754994479331057859347279421152883155043218263254976842483835253219105009503176144
INT (little endian) : 570617459493877713649475153760083387553114932299150094258197821559881096357850356321435736346001916295658808607102043114157953211076517692959373923819366770228232755598854839953543163856539806208261521953434405944516703935144717563814685599349407886676161531174216289149642732256203835947238728183784429314
STR : b"\x02W$\xb6\x07z\xa7H\n\xd2\xc8\x84\xaa\xdd\xe4\x85\xbe0\xc7j\xf7\x1d}\xd8\x96\xdf\x92\x89gl\x8d\xbb\x07j7^\xb4\xec\xddTW0\x93\x01\x90\xa9\x03\xe6\xfb\xcc5'1\x97}n5\xf8{\xd1!\xc3\xc5\xca\xde\r\x80\x1avR\xec\xc0\x11\x9b(\x8e.\xcf\x00\x87\xc1\r\x08\x9a\xc4z3\xafn\xd4\x9c\xa6\xd0h?\xa9]\xb0\xfa=\xacim9H1Q\x1f\xf6\xd9\xfb[\xd4\x8d\xfe>\x8e\xd5Q.E\xd2\xe3\xc8\xa6\x05\xd0"
```
