### ISSUE TITLE
ValueError: no invmod for given @a and @n

### ISSUE THREAD

**Issue by AstralPresence** [Ganapati/RsaCtfTool#121]
[*] Performing factordb attack on rootauthorizedsshkey.pub.
Traceback (most recent call last):
  File "/opt/RsaCtfTool/RsaCtfTool.py", line 262, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/opt/RsaCtfTool/lib/rsa_attack.py", line 192, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/opt/RsaCtfTool/attacks/single_key/factordb.py", line 85, in attack
    priv_key = PrivateKey(
  File "/opt/RsaCtfTool/lib/keys_wrapper.py", line 101, in __init__
    self.d = invmod(e, self.phi)
  File "/opt/RsaCtfTool/lib/rsalibnum.py", line 24, in invmod
    raise ValueError("no invmod for given @a and @n")
ValueError: no invmod for given @a and @n

This error occurred while running "python3 /opt/RsaCtfTool/RsaCtfTool.py --publickey rootauthorizedsshkey.pub --private "

however, an older version of your code which was forked here https://github.com/xmunoz/RsaCtfTool was able to give the desired output by doing Wiener's attack.

Thanks for the great work!

**Comment by Ganapati** [comment]
Can you give me the publickey for tests & patch?

**Comment by AstralPresence** [comment]
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKBgQYHLL65S3kVbhZ6kJnpf072
YPH4Clvxj/41tzMVp/O3PCRVkDK/CpfBCS5PQV+mAcghLpSzTnFUzs69Ys466M//
DmcIo1pJGKy8LDrwdpsSjVmvSgg39nCoOYMiAUVF0T0c47eUCmBloX/K8QjId6Pd
D/qlaFM8B87MHZlW1fqe6QKBgQVY7NdIxerjKu5eOsRE8HTDAw9BLYUyoYeAe4/w
Wt2/7A1Xgi5ckTFMG5EXhfv67GfCFE3jCpn2sd5e6zqBoKlHwAk52w4jSihdzGAx
I85LArqOGc6QoVPS7jx5h5bK/3Oqm3siimo8O1BJ+mKGy9Owg9oZhBl28CfRyFug
a99GCw==
-----END PUBLIC KEY-----

**Comment by theactiveone** [comment]
I had a similar issue:
```
python RsaCtfTool.py --uncipher 233513657019112884402526805488045370699582431208837327188011754051873366392912615473456879232775441297348575281668436579597550370650631661975571589273446285001599323237766574393604714546532580626995048525342973685151862660541374458192194273262940963973164183465013126180350287462022130030595435332698418086061976121986842201005640863232000 -e 3 -n 125130043811804848071621722813146295213721263490749897341144498015047054878231597593120048448069477578767859816785798546510722467452305509931893011927867514122013598496819660392943091608382047677702362802799085703370063497015671978816508707932127744034075928363720201063378356268212406844829575209485500902859 --attack factordb
```

resulted in:
```
[*] Performing factordb attack on /tmp/tmph0qmeq6q.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 262, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/maximilian/RsaCtfTool/lib/rsa_attack.py", line 193, in attack_single_key
    self, self.publickey, self.cipher
  File "/home/maximilian/RsaCtfTool/attacks/single_key/factordb.py", line 89, in attack
    n=int(publickey.n),
  File "/home/maximilian/RsaCtfTool/lib/keys_wrapper.py", line 101, in __init__
    self.d = invmod(e, self.phi)
  File "/home/maximilian/RsaCtfTool/lib/rsalibnum.py", line 24, in invmod
    raise ValueError("no invmod for given @a and @n")
ValueError: no invmod for given @a and @n
```

I got the same error on python 3.6.9 on Ubuntu WSL and 3.6.9 on Ubuntu (native). 

That does not only cashes this specific attack it also breaks the whole program and prevents from executing the other attacks if ´´´--attach all´´´ or the parameter is not specified at all. 

Thanks a lot for the cool tool!

**Comment by Ganapati** [comment]
It seems to be fixed with commit patching the p == n == q problem with factordb, can you confirm this?

**Comment by Neroli-realy** [comment]
same issue for me
```
python RsaCtfTool.py -n 3283820208958447696987943374117448908009765357285654693385347327161990683145362435055078968569512096812028089118865534433123727617331619214412173257331161 -e 65537 --uncipher 2152534604028570372634288477962037445130495144236447333908131330331177601915631781056255815304219841064038378099612028528380520661613873180982330559507116
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmpfgp7vgq8.
[*] Performing boneh_durfee attack on /tmp/tmpfgp7vgq8.
[*] Performing comfact_cn attack on /tmp/tmpfgp7vgq8.
[*] Performing cube_root attack on /tmp/tmpfgp7vgq8.
[*] Performing ecm attack on /tmp/tmpfgp7vgq8.
[*] ECM Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
[*] Performing ecm2 attack on /tmp/tmpfgp7vgq8.
[*] ECM2 Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
[*] Performing factordb attack on /tmp/tmpfgp7vgq8.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 265, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/run/media/neroli/Data/CTF/hacklu/crypto/public/RsaCtfTool/lib/rsa_attack.py", line 192, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/run/media/neroli/Data/CTF/hacklu/crypto/public/RsaCtfTool/attacks/single_key/factordb.py", line 89, in attack
    priv_key = PrivateKey(
  File "/run/media/neroli/Data/CTF/hacklu/crypto/public/RsaCtfTool/lib/keys_wrapper.py", line 101, in __init__
    self.d = invmod(e, self.phi)
  File "/run/media/neroli/Data/CTF/hacklu/crypto/public/RsaCtfTool/lib/rsalibnum.py", line 24, in invmod
    raise ValueError("no invmod for given @a and @n")
ValueError: no invmod for given @a and @n
```

**Comment by Ganapati** [comment]
Fixed in latest commit
