### ISSUE TITLE
Add SageMath as Requirement to README.md

### ISSUE THREAD

**Issue by theactiveone** [Ganapati/RsaCtfTool#123]
I installed all requirement, optional-requirements and os specific requirements according to the `README.md` but still got:

```
...
Can't load boneh_durfee because sage is not installed
Can't load ecm because sage is not installed
Can't load ecm2 because sage is not installed
Can't load qicheng because sage is not installed
Can't load roca because sage is not installed
Can't load smallfraction because sage is not installed
...
```

I took a look at `lib/utils.py` where the error comes from ([specific lines](https://github.com/Ganapati/RsaCtfTool/blob/7be043fdffaaeff9881575ca346953d0d99071f1/lib/utils.py#L25)):

```
def sageworks():
    """Check if sage is installed and working
    """
    try:
        sageversion = subprocess.check_output(["sage", "-v"], timeout=10)
    except OSError:
        return False

    if "SageMath version" in sageversion.decode("utf-8"):
        return True
    else:
        return False
```
There you can see that not only the `sagemath` package is required but also the application sage. After installing sagemath on ubuntu ([via apt-get](https://wiki.ubuntuusers.de/SAGE/)) everything works fine.

Please add this requirement to the `README.md`

**Comment by Ganapati** [comment]
Done.
