### ISSUE TITLE
Yafu SIQS is not working.

### ISSUE THREAD

**Issue by gabriellaquattrone** [Ganapati/RsaCtfTool#125]
Running python3 RsaCtfTool.py -n [arg here] -e [arg here] --uncipher [arg here] --private --attack all I get

![image](https://user-images.githubusercontent.com/30669574/88944923-59487880-d25b-11ea-9055-d06458fdff2d.png)

**Comment by Ganapati** [comment]
fixed with bug #117

**Comment by maniac-en** [comment]
Even for me, when I run the latest version as of today, it  says `[!] Yafu SIQS is not working.`

OS: Ubuntu 20.04
latest commit hash(smiple) as of posting the issue: bd5d6b9
Installed via git :)
