### ISSUE TITLE
utils.py has a syntax error ,how to deal with the problem

### ISSUE THREAD

**Issue by liguandao** [Ganapati/RsaCtfTool#131]
File "RsaCtfTool-master/lib/utils.py", line 122
    logger.info(f"HEX : 0x{c.hex()}")
                                   ^
SyntaxError: invalid syntax

**Comment by Ganapati** [comment]
Can you re-check with latest version and if it doesn't help, paste me your command line ?

**Comment by liguandao** [comment]
i check it with latest version，i just try to execute python RsaCtfTool.py -h then return the invalid syntax exception
![QQ截图20201012154715](https://user-images.githubusercontent.com/23159664/95719325-3c401500-0ca2-11eb-825b-cd85b123b58f.png)

**Comment by Ganapati** [comment]
I assume `python` is a symlink to python2, can you try `python3 ./RsaCtfTool.py -h` ?

**Comment by liguandao** [comment]
> I assume `python` is a symlink to python2, can you try `python3 ./RsaCtfTool.py -h` ?

the same exception，python3 version is 3.5.2 
![QQ截图20201012155635](https://user-images.githubusercontent.com/23159664/95720415-cb99f800-0ca3-11eb-867b-69ac0256bbd7.png)

**Comment by Ganapati** [comment]
I have no issue on python 3.8.6, but on the latest version, the logger stuff is on line 123, did you pull it ?
I have no clue about your bug, first time someone is having this...

**Comment by liguandao** [comment]
> I have no issue on python 3.8.6, but on the latest version, the logger stuff is on line 123, did you pull it ?
> I have no clue about your bug, first time someone is having this...

i try to repull and execute the same command, as you say, the issue of logger stuff is on line 123 ,how to deal with it

**Comment by Ganapati** [comment]
no idea, maybe encoding issue with your system...

**Comment by baninhadin** [comment]
im facing the same issue

**Comment by ByeRose** [comment]
me too
