### ISSUE TITLE
error

### ISSUE THREAD

**Issue by leijurv** [Ganapati/RsaCtfTool#14]
`python RsaCtfTool.py  --publickey key.pub --private`

```
Traceback (most recent call last):
  File "RsaCtfTool.py", line 488, in <module>
    attackobj.attack()
  File "RsaCtfTool.py", line 391, in attack
    getattr(self, attack.__name__)()
  File "RsaCtfTool.py", line 369, in Pollard_p_1
    self.pub_key.p, self.pub_key.q = pollard_P_1(self.pub_key.n)
TypeError: 'int' object is not iterable
```

**Comment by Br4m3000Dev** [comment]
I have got the exact same error, am using the same command aswell. 

Any chance you are searching for the HTB flag aswell?

**Comment by leijurv** [comment]
I'm currently doing easyctf =)

**Comment by Ganapati** [comment]
Can you give me your public key ? I'll try to fix this.

**Comment by Ganapati** [comment]
I tried with the chall "RSA return" from easyctf 2018 : 

/m/v/t/c/RsaCtfTool ❯❯❯ ./RsaCtfTool.py -n 9637828843823500407917687664441327784714605952794831018467094508166140790258515855681653788687192363262499178812675284846293988948568322307302995971433129 -e 65537 --uncipher 744372384092422293657230440929981477879274068697788092531354927993093987582083018137886004402518974542009040817374858469786477527000745005045012289929736
[+] Clear text : b'easyctf{4b8xofjwvy4rqkbuba}'

same with rsa_v (https://github.com/zst123/easyctf_iv-2018-writeups/tree/master/Solved/RSA_v) :

/m/v/t/c/RsaCtfTool ❯❯❯ ./RsaCtfTool.py --publickey '/tmp/pubkey*' --uncipher 7117565509436551004326380884878672285722722211683863300406979545670706419248965442464045826652880670654603049188012705474321735863639519103720255725251120
[+] Clear text : b'easyctf{keblftftzibatdsqmqotemmty}'

No problem for me.
