### ISSUE TITLE
[Feature request] Add p=(Ds^2+1)/4 type primes factorization method

### ISSUE THREAD

**Issue by maple3142** [Ganapati/RsaCtfTool#154]
Sage implementation: https://github.com/crocs-muni/cm_factorization
Original paper: https://crocs.fi.muni.cz/_media/public/papers/2019-secrypt-sedlacek.pdf

I think can it should be easy to be added to this project as there are sage implementation, but it need an extra parameter **D** to work, so I am not sure how should this be added?

**Comment by daedalus** [comment]
Hi pr: #155
