### ISSUE TITLE
Hi thanks for such a nice repository

### ISSUE THREAD

**Issue by sumitdadhich** [Ganapati/RsaCtfTool#162]
Thanks for such a nice repository I wanted to It works fast on compressed public keys or on uncompressed public keys

**Comment by Ganapati** [comment]
I don't understand your request about (un)compressed public keys, can you explain?

**Comment by sumitdadhich** [comment]
SSL public keys and bitcoin public keys are same but your software don't
work on Bitcoin public keys

**Comment by Ganapati** [comment]
can you give me some test case and i'll see if I have some time.

**Comment by sumitdadhich** [comment]
Sure! Private
key 18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725
uncompressed
publickey 0450863AD64A87AE8A2FE83C1AF1A8403CB53F53E486D8511DAD8A04887E5B23522CD470243453A299FA9E77237716103ABC11A1DF38855ED6F2EE187E9C582BA6
compressed
key 0250863AD64A87AE8A2FE83C1AF1A8403CB53F53E486D8511DAD8A04887E5B2352 more
please check
https://www.freecodecamp.org/news/how-to-create-a-bitcoin-wallet-address-from-a-private-key-eca3ddd9c05f/

**Comment by Ganapati** [comment]
Sorry, it's a cool idea but I have no time for this kind of new feature.
You can provide a pull request if you want :)
