### ISSUE TITLE
TypeError in comfact_cn attack

### ISSUE THREAD

**Issue by adityabadhiye** [Ganapati/RsaCtfTool#163]
./RsaCtfTool.py --publickey ./pub.pem --uncipherfile ./text.enc --private

[*] Testing key ./pub.pem.
[*] Performing binary_polinomial_factoring attack on ./pub.pem.
[*] Performing boneh_durfee attack on ./pub.pem.
[*] Performing cm_factor attack on ./pub.pem.
100%|█████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.63it/s]
[*] Performing comfact_cn attack on ./pub.pem.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 283, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/mnt/c/CTF/RsaCtfTool/lib/rsa_attack.py", line 194, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
TypeError: cannot unpack non-iterable NoneType object

**Comment by adityabadhiye** [comment]
[rsa.zip](https://github.com/Ganapati/RsaCtfTool/files/5845218/rsa.zip)

public key and encrypted file

**Comment by Ganapati** [comment]
Fixed in new commit (https://github.com/Ganapati/RsaCtfTool/commit/8e7422b8d405e411139eac65931b4d44c72362c2)
