### ISSUE TITLE
another TypeError in cm_factor attack

### ISSUE THREAD

**Issue by adityabadhiye** [Ganapati/RsaCtfTool#164]
[*] Performing cm_factor attack on ./pub.pem.
100%|█████████████████████████████████████████████████| 6/6 [04:20<00:00, 43.39s/it]
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 283, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/aditya/ctf/RsaCtfTool/lib/rsa_attack.py", line 194, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/aditya/ctf/RsaCtfTool/attacks/single_key/cm_factor.py", line 46, in attack
    if sageresult > 0:
TypeError: '>' not supported between instances of 'bytes' and 'int'

**Comment by daedalus** [comment]
Hi @adityabadhiye would you like to share your pub.pem? so we can debug this issue.
Thanks

**Comment by Ganapati** [comment]
@daedalus i'm on it, last tests before commit :)

**Comment by Ganapati** [comment]
fixed in latest commit !

**Comment by daedalus** [comment]
cheers!

**Comment by adityabadhiye** [comment]
[rsa.zip](https://github.com/Ganapati/RsaCtfTool/files/5850520/rsa.zip)
@daedalus see this has pub key and enc file
