### ISSUE TITLE
attack_single_key() missing 1 required positional argument: 'attacks_list'

### ISSUE THREAD

**Issue by adityabadhiye** [Ganapati/RsaCtfTool#171]
./RsaCtfTool.py --publickey "*.pub" --private
[*] Multikey mode using keys: pubkey1.pub, pubkey2.pub
[*] Performing commonfactors attack.
[*] Performing hastads attack.
[*] Performing same_n_huge_e attack.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 277, in <module>
    found = attackobj.attack_multiple_keys(args.publickey, attacks_list)
  File "/mnt/c/ctf/RsaCtfTool/lib/rsa_attack.py", line 153, in attack_multiple_keys
    self.priv_key, unciphered = attack_module.attack(
  File "/mnt/c/ctf/RsaCtfTool/attacks/multi_keys/same_n_huge_e.py", line 27, in attack
    result = attack_rsa_obj.attack_single_key(tmpfile.name)
TypeError: attack_single_key() missing 1 required positional argument: 'attacks_list'

error with multiple keys

**Comment by Ganapati** [comment]
can you give me more details ? maybe the public keys ?

**Comment by adityabadhiye** [comment]
[key.zip](https://github.com/Ganapati/RsaCtfTool/files/6056350/key.zip)

**Comment by Ganapati** [comment]
Fixed in latest commit
