### ISSUE TITLE
This destroys the RSA cryptosystem

### ISSUE THREAD

**Issue by daedalus** [Ganapati/RsaCtfTool#175]
Hello

Claus Peter Schnorr a known cryptographer, in a recent publication May/1/2021, claims that he can break rsa fast and easy with SVP algorithms, the paper contains his words: "**_This destroys the RSA cryptosystem_**"

SVP is a class of lattice reduction algorithm, this kind of algorithm where previously covered by  _Coppersmith et al_ for factoring certain class of composite integer.

Here is the white paper: https://eprint.iacr.org/2021/232

I'm looling forward for an implementation of the attack.

**Comment by daedalus** [comment]
Found this:

https://github.com/lducas/SchnorrGate

**Comment by pedroelbanquero** [comment]
> Found this:
> 
> https://github.com/lducas/SchnorrGate

works really slow, somebody have a good result with that ?

**Comment by daedalus** [comment]
I think i got it working:

https://github.com/daedalus/SchnorrGate

I have been able to factor integers tweaking the n variable. I think it depends on the size of the integer to factor thus bigger n is equal to more relations and more chances of factoring, I borrowed code from pollard's p-1 algorithm.

I currently testing it

**Comment by pedroelbanquero** [comment]
wow nice !!

**Comment by daedalus** [comment]
I think it doenst work, the tests are not encouraging.
