### ISSUE TITLE
Warning: Modulus too large for SIQS attack module

### ISSUE THREAD

**Issue by sasha2002** [Ganapati/RsaCtfTool#18]
# ./RsaCtfTool.py --publickey public.key --verbose
[*] Performing Pollard_p_1 attack.
[*] Performing hastads attack.
[*] Performing factordb attack.
[*] Performing pastctfprimes attack.
[*] Loaded 71 primes
[*] Performing noveltyprimes attack.
[*] Performing smallq attack.
[*] Performing wiener attack.
[*] Performing comfact_cn attack.
[*] Performing fermat attack.
[*] Performing siqs attack.
[*] Warning: Modulus too large for SIQS attack module

**Comment by Ganapati** [comment]
It's not a bug, it's an information, this attack can not be performed in your test case.

**Comment by sasha2002** [comment]
@Ganapati  And how is possible to factorize it? I'm ok with large amount of time.
