### ISSUE TITLE
Attack run order

### ISSUE THREAD

**Issue by mendel3** [Ganapati/RsaCtfTool#182]
Currently attacks are run in alphabetical order. I think it would be really nice if there was an argument that ran attacks (very roughly) based on the estimated time that they take, which would greatly speed up runtime. Thanks for considering my suggestion!

**Comment by Ganapati** [comment]
How about a "slow, medium, fast" attribute by attack (one in each attack class) and ordering by this information ?
Do you think it will solve your problem?

**Comment by Ganapati** [comment]
Ok, this idea was a little improvement and now I'm refactoring the whole attack system... This issue will not be fixed today !

**Comment by Ganapati** [comment]
Ordering by speed is implemented, but I have no time nor bravery to test each attack and set the correct time estimation (slow, medium, fast).
You can make a pull request :)
