### ISSUE TITLE
[bug] Installed requirements.txt but Crypto still not found

### ISSUE THREAD

**Issue by 0xmmalik** [Ganapati/RsaCtfTool#183]
I installed `requirements.txt` using `pip install -r requirements.txt`. It installed all the packages, however, I still get this error:

```
Traceback (most recent call last):
  File "RsaCtfTool.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
```

Are there conflicting dependencies?

**Comment by Ganapati** [comment]
Try to install pycrypto (https://pypi.org/project/pycrypto/).
If it fix the bug, i'll update the requirements.txt.
