### ISSUE TITLE
Add a GitHub workflow for testing

### ISSUE THREAD

**Issue by capra314cabra** [Ganapati/RsaCtfTool#186]
After finishing tasks of adding tests for RsaCtfTool, it should improve its maintainability more if we create a GitHub workflow for testing it, I think.

**Comment by Ganapati** [comment]
Very good idea, I've never used github workflow before, so we can add it after implementing tests for each attack.

**Comment by capra314cabra** [comment]
If you have no time to add the feature, you can mention me on this thread for letting me implement it :)

**Comment by Ganapati** [comment]
YAY !!
