### ISSUE TITLE
 "No module named 'lib.rsa_attack'

### ISSUE THREAD

**Issue by VinuantLiu** [Ganapati/RsaCtfTool#187]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
ModuleNotFoundError: No module named 'lib.rsa_attack'

I've done all the reqs, but this still shows up.

**Comment by daedalus** [comment]
Hi,

There is no main.py file in the project.
Can you share what you are trying to execute?

**Comment by VinuantLiu** [comment]
I took the code from the RSACTFTool.py file and plugged it into repl.it

https://pastebin.com/Y8aYsphx

**Comment by daedalus** [comment]
That is not a supported way of running the project.

**Comment by Ganapati** [comment]
As daedalus says, RsaCtfTool was designed/built this way.
