### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decrypt'

### ISSUE THREAD

**Issue by N1CK5V** [Ganapati/RsaCtfTool#190]
Hi. When running RsaCtfTool with p,q,e and ciphertext gives error with a traceback:
```Traceback (most recent call last):
  File "RsaCtfTool.py", line 219, in <module>
    unciphers.append(priv_key.decrypt(args.uncipher))
AttributeError: 'NoneType' object has no attribute 'decrypt'```

**Comment by VishDroid-dev** [comment]
Yeah!, Im also facing the same problem

**Comment by Ganapati** [comment]
Can you both provide me your inputs (p, q, e, c) ? I'll try to fix this, but I need test data.

**Comment by N1CK5V** [comment]
p = 151504136086085116766143566124150275674073392929821608731193313303579549567486780984882103878189021716475112187664571076380701312144707968796469474077396203079356104319166539457117762979236714826426908047910529451429037552027255450267166159899155876867790669696867818896423172168830285791913854195932438702321
q = 103830664295009091893886752305087173101905116416231118984740125697489572383920741106883033358012404414250903398273361420080940861355058896027909558044477593238426139173175903469841531670082355641543985372882381822644581374082868518234109972478903771291945965032201075848195104712153515556622192413687460682033
e = 112
c = 7376083179301871727319662441290512768979499624954698397165424050024666168943377478129926304132046879741349597229411809080978573590530226067752606719487158834511752336008287600324551704896881690547279678544392014784520001523240813365339789395536491039305623640655624806350548548554437985830405020169663539939018239643445566882380359742208558132490655657280619850656880232036155057833081215187526442724687828214045430674207843841122060416377750502505640447395732809699800028565067081780511133517020113861405502897034245617267331520262877918693182867532420288135211820606290453667200638642871988519470430475958049806666

**Comment by Ganapati** [comment]
Can you give me a part of plaintext expected result ?
For now, i'm getting some garbage :
```'\x03\xe2\xe5\xf0c\x88\xe3"\xdf\\\xfb\xab\xa3\xa3\xcdm\x9dA\xcb\x85\xee\xa0zS\xb7\xec\xde\x08\xdbH?\x93\xc5\xec\xe8!\x0b\x1ce.\xc3cQ\xa8]Y\x9e~\xeb\xc0P\x0b\x94\xa2\xc0\xc5\xec$L\xdf\xc1R\xde\x9c\xbd\xaa\xab\xf5+\x12*/\xb1v\x02\x9e\xfe\x84\xc7\x0c\x9c\xdc_)\x82\xda\xe3\x9a\xa6\xc6\xd5\xc9)\x0b9\x17\xe2\x04\xdc\xb4Re\x88\x99m\\Q7`\x87O\x99\xf7\xcc\x96\x08\x99U\x96\x1bN\xd2"\x04\xa5c\x89\xbc\xc9\xef\xd2\xd0\xa9d\x06N\x1a\x8bG>\xa6Y\xcd\x08\x02\xeeZ[\xf7\xb1\xc4\xef\t\x19\x0c+\xc9/\xa8\xbb\x96\x13\xabkL\xfcs#\xfes^\xb2\xb6)\x8a\xe7`\xbc\x8b\xae\xff\x11\xba\xa0X\xa1\xc0\xcd\n\x17\x98Z\xfbS\x8fO\x17\xe4IF\xd1\\)\xb9\x10yoe\xd5\xbdS\x833u\x15\xacK00R\x04468\xb4l\xc9\xa9\x01\xec\\I\x0e\xcdk\xde\xe5\xe3\xfb\x1b\xca?\x1e\x81\xdd5A.\xcfQ\xc4\xff\xec|\x1d\xf2'```

**Comment by Ganapati** [comment]
Looks like your p, q and e can't generate a valid RSA key.
I changed the code to handle this issue !
Thx !

**Comment by M4GNV5** [comment]
I still get that error even with the newest version, it looks like 4793422a0d04c1c69a7bae94f80185d5a62648f3 did not fix it?

```
$ git log | head -n 5
commit 4793422a0d04c1c69a7bae94f80185d5a62648f3
Author: Ganapati <ganapati@foobar.baz>
Date:   Sun Mar 21 10:58:42 2021 +0100

    Fix issue #190

$ python3 RsaCtfTool.py -n 145902412361478782344770381873783700413638083575664796147183684992615987925480426688706400688307583005196450858827113757408777361940584125700594767997877530445777012630266331221234501260829837820315200747919668506933176146599166089445798737129024362167061966283411487243534460764772316650320961711082540676899 -e 1480170 \
-p 12037827528067911684278967221392433256129944002157200272548317200308481572950474775891360447285969682243206009995242277136633522897723532096467191105943909 \
-q 12120327527644543811107783655014863098833219936714394976342507913322405566177432644931575840816861543106701611662013978324877080018872656490603706071067111 \
--uncipher 31103221150639270981602750809035063173340249285095214543297188405667428764463716622426909278361960304980002156514891787988530074253809585917244290775992848588396219195251026173987370562041567149172370957556079284549807413525629606589613049164963338717932275784245874484894527968034024267707369481475042323854 \
--dumpkey --private

Traceback (most recent call last):
  File "RsaCtfTool.py", line 232, in <module>
    unciphers.append(priv_key.decrypt(args.uncipher))
AttributeError: 'NoneType' object has no attribute 'decrypt'
```

**Comment by daedalus** [comment]
I think the problem in both cases lies in e being not prime.

**Comment by Ganapati** [comment]
Looks like I patched only one place and two were required... My bad!
It's ok now
