### ISSUE TITLE
Add a flag to disable progress bars

### ISSUE THREAD

**Issue by capra314cabra** [Ganapati/RsaCtfTool#198]
There are progress bars which show how many numbers it has prossesed. That is a great feature in many cases, but when we run it on a test workflow, it prints tons of meaningless lines.
So it would be greater if we have a flag like `--disable-prog` which disables progress bars.
According to tqdm/tqdm#1, `tqdm` has an option.

**Comment by Ganapati** [comment]
thx for commit
