### ISSUE TITLE
Solve bottleneck in testing workflow

### ISSUE THREAD

**Issue by daedalus** [Ganapati/RsaCtfTool#209]
The tests workflow are consuming too much time and eventualy do timeout. We need to find a way to cache them to save some time with caches.
apt and pypi are the bottlenecks I think.

**Comment by VKECE** [comment]
private argument is not set, the private key will not be displayed, even if recovered.
Traceback (most recent call last):
  File "/home/kali/RsaCtfTool/./RsaCtfTool.py", line 186, in <module>
    uncipher_array.append(n2s(uncipher))
  File "/home/kali/RsaCtfTool/lib/rsalibnum.py", line 98, in n2s
    s = hex(n)[2:].rstrip("L")
TypeError: 'list' object cannot be interpreted as an integer

Please Help Me :( 

testctf.sh -> run
[https://i.imgur.com/xkfUUlJ.png](url)

**Comment by VKECE** [comment]
![2021-04-20 04_03_53](https://user-images.githubusercontent.com/1547714/115321892-7f1d0100-a18d-11eb-8792-45503e8b04e9.png)
error screenshot

**Comment by daedalus** [comment]
> private argument is not set, the private key will not be displayed, even if recovered.
> Traceback (most recent call last):
> File "/home/kali/RsaCtfTool/./RsaCtfTool.py", line 186, in
> uncipher_array.append(n2s(uncipher))
> File "/home/kali/RsaCtfTool/lib/rsalibnum.py", line 98, in n2s
> s = hex(n)[2:].rstrip("L")
> TypeError: 'list' object cannot be interpreted as an integer
> 
> Please Help Me :(
> 
> testctf.sh -> run
> [https://i.imgur.com/xkfUUlJ.png](url)

This is unrelated to this issue, please file a new one.

**Comment by VKECE** [comment]
sorry ;)

**Comment by Ganapati** [comment]
Don't know how tosolve this... I close it but still search a solution !
