### ISSUE TITLE
TypeError: 'list' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by VKECE** [Ganapati/RsaCtfTool#219]
private argument is not set, the private key will not be displayed, even if recovered.
Traceback (most recent call last):
File "/home/kali/RsaCtfTool/./RsaCtfTool.py", line 186, in
uncipher_array.append(n2s(uncipher))
File "/home/kali/RsaCtfTool/lib/rsalibnum.py", line 98, in n2s
s = hex(n)[2:].rstrip("L")
![2021-04-20 04_03_53](https://user-images.githubusercontent.com/1547714/115321951-a673ce00-a18d-11eb-9bbb-92025c16a786.png)
Please Help Me :(

testctf.sh -> run
https://i.imgur.com/xkfUUlJ.png

**Comment by ahessmat** [comment]
I believe the issue lies in line 185 of RsaCtfTool.py:

uncipher = get_base64_value(unciphers)

If I'm tracing the program execution correctly, it's erroneously calling get_base64_value() on an empty list object. I commented out that line and the program worked fine afterwards.

Regrettably, I'm not that proficient with Git (yet), so I don't know how to properly initiate a push request with the fix.

**Comment by ahessmat** [comment]
I (think?) I've created a pull request to resolve the issue.

**Comment by Ganapati** [comment]
can you paste me your command here so i'll check this ?

**Comment by Ganapati** [comment]
Ok, it's fixed. A typo (unciphers != uncipher)
thx !

**Comment by Ganapati** [comment]
```
~/p/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py -n 14641034851154010900546719241402474912998133209474218975103977449764205791710698412984067810848509509669017831054155506105922179074286929418416328797379636196613023210067141695123691351917498467761961980966631958692894027223505926821780581042313171803091956255639968110368314924456998367348008686435826036480738828760312467761150839006456972383 -e 65537 --uncipher 7102577393434866594929140550804968099111271800384955683330956013020579564684516163830573468073604865935034522944441894535695787080676107364035121171758895218132464499398807752144702697548021940878072503062685829101838944413876346837812265739970980202827485238414586892442822429233004808821082551675699702413952211939387589361654209039260795229 --attack ecm2 --timeout 60
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp0y8ubutx.
[*] Performing ecm2 attack on /tmp/tmp0y8ubutx.

Results for /tmp/tmp0y8ubutx:

Unciphered data :
HEX : 0x7069636f4354467b746f6f5f6d616e795f666163743072735f343831373938357d
INT (big endian) : 13016382529449106065933618925167173598170118383294989999418818728072538624636285
INT (little endian) : 14498083073962587393323532538040852713352948827962850906000193971067545442281840
STR : b'picoCTF{REDACTED}'
```
