### ISSUE TITLE
How to solve a problem ?

### ISSUE THREAD

**Issue by NikitaSolncev** [Ganapati/RsaCtfTool#22]
C:\Users\HP>C:\Python27\RsaCtfTool\RsaCtfTool.py
Traceback (most recent call last):
  File "C:\Python27\RsaCtfTool\RsaCtfTool.py", line 654, in <module>
    attackobj = RSAAttack(args)
  File "C:\Python27\RsaCtfTool\RsaCtfTool.py", line 103, in __init__
    if '*' in args.publickey or '?' in args.publickey:
TypeError: argument of type 'NoneType' is not iterable

**Comment by mattweidner** [comment]
This seems to indicate that you have not specified any command line arguments. Try running `C:\Python27\RsaCtfTool\RsaCtfTool.py -h` or `C:\Python27\RsaCtfTool\RsaCtfTool.py --help`

**Comment by mattweidner** [comment]
Relevant pull request
https://github.com/Ganapati/RsaCtfTool/pull/26

**Comment by Ganapati** [comment]
fixed.
