### ISSUE TITLE
ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by stwtgithub** [Ganapati/RsaCtfTool#226]
python3 RsaCtfTool.py --publickey "/home/kali/RsaCtfTool/file/rsa_public_key.pem_bak" --private --verbosity INFO                                                                                    2 ⚙

[*] Testing key /home/kali/RsaCtfTool/file/rsa_public_key.pem_bak.
[*] Performing smallq attack on /home/kali/RsaCtfTool/file/rsa_public_key.pem_bak.
[*] Performing pastctfprimes attack on /home/kali/RsaCtfTool/file/rsa_public_key.pem_bak.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113/113 [00:00<00:00, 691907.08it/s]
[*] Performing system_primes_gcd attack on /home/kali/RsaCtfTool/file/rsa_public_key.pem_bak.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 377, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/RsaCtfTool/lib/rsa_attack.py", line 242, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/kali/RsaCtfTool/attacks/single_key/system_primes_gcd.py", line 21, in attack
    primes = load_system_consts()
  File "/home/kali/RsaCtfTool/lib/system_primes.py", line 1300, in load_system_consts
    primes_tmp0 = sorted(set(primes_tmp0))
  File "/home/kali/RsaCtfTool/lib/system_primes.py", line 1299, in <lambda>
    primes_tmp0 = map(lambda x: int(x, 16), primes_tmp0)
ValueError: invalid literal for int() with base 16: ''

how to fix this, please help me

**Comment by Ganapati** [comment]
Fixed

**Comment by stwtgithub** [comment]
sry, i updated latest code , but no work

**Comment by Ganapati** [comment]
can you give me your public key for testing? can't reproduce on my setup.

**Comment by stwtgithub** [comment]
> can you give me your public key for testing? can't reproduce on my setup.
OK，

-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKBgQKP/53T5v6XgWSet/5ekwPP
aWNHxBELxLo5afCxFmmEDFHYGmhCtt8rCQ8hzXbUNxqMDkcEjJZeyltGkTr7uNoF
IHKgVm1wOcYYq6kGV1mwWeKeSF3FBhoWrGMSlDjZNU5l31dHVGuF2z1pmBnEt3Mt
+SfHCEpdUtbm1qrBRGI0JQKBgQH4+6QQBS337aNGLxqs1p5AdgQzyjNXZ81zBaPQ
kIBaX9QF3W7qcOmPDKHhzyVHSGcb8MmABsIO7h1ieQQ1Cf56mCOLQ5FgpWEtpx6Q
RRToEoBhfjB8PNMxP6TG/KMxWdBEH7sY2DyvS9Rva5KXqAoULdab8aNXzLXkwgC2
2Q8Vow==
-----END PUBLIC KEY-----

**Comment by Ganapati** [comment]
I've tried your key with all attacks and it works, and i've tested with the bugged-attack and there is no more bug, can you git pull/retry please?

**Comment by stwtgithub** [comment]
> I've tried your key with all attacks and it works, and i've tested with the bugged-attack and there is no more bug, can you git pull/retry please?

oh my god , it works 
just clone again instead of git fetch --all ,and it works
thanks very much

**Comment by Ganapati** [comment]
:)
