### ISSUE TITLE
Crash when using multiple public keys

### ISSUE THREAD

**Issue by mda01** [Ganapati/RsaCtfTool#231]
Hello,

I have a fatal error when using the multiple keys option:

Command:
`python3 RsaCtfTool.py --publickey "/home/kali/[...]/*.pem" --private`

Result:
```
[*] Multikey mode using keys: /home/kali/[...]/clef2_pub.pem, /home/kali/[...]/clef1_pub.pem, /home/kali/[...]/clef0_pub.pem
Traceback (most recent call last):
  File "/home/kali/RsaCtfTool/RsaCtfTool.py", line 371, in <module>
    found = attackobj.attack_multiple_keys(args.publickey, attacks_list)
  File "/home/kali/RsaCtfTool/lib/rsa_attack.py", line 198, in attack_multiple_keys
    self.pre_check_attack(self.publickeys)
AttributeError: 'RSAAttack' object has no attribute 'publickeys'
```

Note: I replaced my local path with [...]

Edit: To add more details, this occurred in a fresh Kali VM, requirements and optional requirements are both installed.

**Comment by Ganapati** [comment]
Hi, can you send me your keys for reproducing the test on my setup ?

**Comment by mda01** [comment]
[keys.zip](https://github.com/Ganapati/RsaCtfTool/files/6434402/keys.zip)

**Comment by Ganapati** [comment]
Fixed.
