### ISSUE TITLE
The gmpy2 powmod(a,b,c) is about 3.5 times faster than the standard pow(a,b,c)

### ISSUE THREAD

**Issue by maximmasiutin** [Ganapati/RsaCtfTool#235]
See the benchmark of 100000 gmpy2.powmod() vs standard pow() operations for private decryption with RSA 4096 bit key.

```
gmpy: 2.0617496967315674
math: 7.180255651473999
```

Please consider using gmpy2.powmod() instead of the standard pow() whenever possible.

**Comment by daedalus** [comment]
Send a pr, please

**Comment by daedalus** [comment]
Ok I made the pr by myself, thanks for the report.
