### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by BeagelTheBurger** [Ganapati/RsaCtfTool#243]
Hello, if i try using the tool there is no output.

pip install -r "requirements.txt"
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: sympy==1.3 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.3)
Requirement already satisfied: cryptography==3.3.2 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: urllib3==1.24.2 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.24.2)
Requirement already satisfied: requests==2.20.0 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2.20.0)
Requirement already satisfied: gmpy==1.17 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.17)
Requirement already satisfied: gmpy2==2.1.0b5 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.1.0b5)
Requirement already satisfied: pycryptodome==3.9.7 in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (3.9.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages/tqdm-4.32.1-py3.9.egg (from -r requirements.txt (line 9)) (4.32.1)
Requirement already satisfied: z3-solver in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (4.8.10.0)
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (from -r requirements.txt (line 11)) (2.6.1)
Requirement already satisfied: bitarray in /home/craxxor/.local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (2.1.0)
Requirement already satisfied: mpmath>=0.19 in /home/craxxor/.local/lib/python3.9/site-packages (from sympy==1.3->-r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: cffi>=1.12 in /home/craxxor/.local/lib/python3.9/site-packages (from cryptography==3.3.2->-r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/craxxor/.local/lib/python3.9/site-packages (from requests==2.20.0->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/craxxor/.local/lib/python3.9/site-packages (from requests==2.20.0->-r requirements.txt (line 5)) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 5)) (2020.6.20)
Requirement already satisfied: pycparser in /usr/lib/python3/dist-packages (from cffi>=1.12->cryptography==3.3.2->-r requirements.txt (line 3)) (2.20)

This is how it looks like when i run it:

python3 ./RsaCtfTool.py -n 35390004486354300347521848565413257959442624589297688131017877221807025004928966206454752329594506530598099849274956709610488234955109039874355077958460196991750855650029096905451 -e 65537 --uncipher 34976328528100445602888072790831380493399287679380757676967266152942525578548886648293955777757882335796410272725253490310142371251759362170135820927390507970457244397459500624458
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp8w8_wryo.

Edit: I use python 3.9.2, is that the problem?

**Comment by hieplpvip** [comment]
This [commit](https://github.com/Ganapati/RsaCtfTool/commit/0b65233b24264a32e44f8f59e4d732849c2a41b8) seems to cause the problem. You can try reverting it:

```shell
git revert 0b65233b24264a32e44f8f59e4d732849c2a41b8
```

**Comment by daedalus** [comment]
Hi
This should do it.
`./RsaCtfTool.py -n 35390004486354300347521848565413257959442624589297688131017877221807025004928966206454752329594506530598099849274956709610488234955109039874355077958460196991750855650029096905451 -e 65537 --uncipher 34976328528100445602888072790831380493399287679380757676967266152942525578548886648293955777757882335796410272725253490310142371251759362170135820927390507970457244397459500624458 --ignore_checks
`

**Comment by BeagelTheBurger** [comment]
It is working now!

Thank you soooooooo much! You can not believe how happy i am now. I was trying to solve this problem for one week now but i am such a noob that i could not figure out the solution myself.

Again thank you so much, you are a hero! it is such a relieve :-)
