### ISSUE TITLE
does this tool never work on number n, e, c anymore?

### ISSUE THREAD

**Issue by diegoxcn** [Ganapati/RsaCtfTool#247]
Hi Ganapati,

     I run into a problem lately when doing some ctfs, if only provide n, e, and c, this tool would only run without give any result, but only message that a temp file is created, but it would work if I break the n into p and q by some other tool like FactorDB.

     So I go over the code, and found that now it would request n with p or q to get all for numbers (n, e, p, q) to proceed, if not, it would simply quit program. I modified only come code so I can make sure of it.
```console
./RsaCtfTool.py -n 73858245204393269120598772974257218874289179816258533748548954836353808000542909731398449660121424717248079724923923284922221800385870164798744402737063530114487159042350959711492581286948377310386675916734743955708759421607349585475823504183537132290212235481788134354234151518170214048887523664730897405647 -e 40185337488228965483088768689361237580655397969352079774015797079626751211817603607155962600219370112069853693506378621129705581863959239984871073674637310005220323695488701830477574210150173980203084059519439551150923764323395592278383658383525721471839777239932693638775164411928659371101425091253226312809 --uncipher 11279019002658132246395680583012680197641520463055015905954159065596263829466315684813964601637222796742820040947867106250604831640789683230174556440623073026811900236014477245382133062014821631152893829897692611106964558955134460480794092202226246351625569961925929573208935964302390747204250124554416009841 --attack wiener
private argument is not set, the private key will not be displayed, even if recovered.
p=  None
q=  None
```

     Does this work as intended? Since from some history posts and issues that this tool can run with only supply n, e, and c very nicely with small fractions of course. And this do provide easy to use on ctfs.

Thank you very much.

**Comment by daedalus** [comment]
Hi,

It should be solved in pr #245 

`
./RsaCtfTool.py -n 73858245204393269120598772974257218874289179816258533748548954836353808000542909731398449660121424717248079724923923284922221800385870164798744402737063530114487159042350959711492581286948377310386675916734743955708759421607349585475823504183537132290212235481788134354234151518170214048887523664730897405647 -e 40185337488228965483088768689361237580655397969352079774015797079626751211817603607155962600219370112069853693506378621129705581863959239984871073674637310005220323695488701830477574210150173980203084059519439551150923764323395592278383658383525721471839777239932693638775164411928659371101425091253226312809 --uncipher 11279019002658132246395680583012680197641520463055015905954159065596263829466315684813964601637222796742820040947867106250604831640789683230174556440623073026811900236014477245382133062014821631152893829897692611106964558955134460480794092202226246351625569961925929573208935964302390747204250124554416009841 --attack wiener --ignore_checks
`

**Comment by diegoxcn** [comment]
Hi, 

    Thanks for quick reply, but I just tried and also checked code, there's no this option exist, my repo is the latest:
RsaCtfTool.py: error: unrecognized arguments: --ignore_checks

Thanks.

**Comment by daedalus** [comment]
Yo need to wait for @Ganapati  to merge the patch

**Comment by spookyfiish** [comment]
daedalus disabled auto check publickey, it should work in the newest version.

**Comment by diegoxcn** [comment]
Thanks, it's working now.
