### ISSUE TITLE
vafu and neca binaries not installed

### ISSUE THREAD

**Issue by Kartibok** [Ganapati/RsaCtfTool#254]
Hi,
Wondered if I could get a pointer as when I run the tool I get the following errors:

- Can't load siqs because yafu binary is not installed
- Can't load neca because neca binary is not installed

There were a number of sage issues that were fixed by following another issue topic and installing the sage binary. However I could not find any details of the yafu and neca binaries.

Thanks in advance - K

**Comment by Ganapati** [comment]
I'll update the readme as soon as i can

**Comment by markuslaube** [comment]
@Kartibok: 

I think the YAFU problem can be solved easily. I have a symlink from

RsaCtfTool /attacks/single_key/yafu

to /usr/local/bin

placed. Alternative you must Change your PATH ....


regards Laubi

**Comment by tomtastic** [comment]
The yafu binary in that location only yields a `segmentation fault` on my Linux x64 system.
