### ISSUE TITLE
Urllib3 version 1.26.5 doesn't seem to have been released yet

### ISSUE THREAD

**Issue by stampyzfanz** [Ganapati/RsaCtfTool#262]
I just downloaded RsaCtfTool and tried to install it but it said "File "C:\Users\<redacted>\git\RsaCtfTool\RsaCtfTool.py", line 16, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'"

When I tried to `pip install urllib3` it said "Requirement already satisfied: urllib3 in c:\users\<redacted>\appdata\local\programs\python\python36-32\lib\site-packages (1.26.3)".

Additionally, when I open python in the directory, and import urllib3, and execute `urllib3.__version__` it gives "1.26.3".

**Comment by Ganapati** [comment]
It looks like 1.26.5 is available on pipy :
https://pypi.org/project/urllib3/
