### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 5) and urllib3==1.26.5 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by fmadotto** [Ganapati/RsaCtfTool#264]
Commit ff6119d7781d237650d0dc18c86fa33837e7731d broke the requirements.txt.

![image](https://user-images.githubusercontent.com/7075143/121534408-7ca68d00-ca01-11eb-9703-77260946a41b.png)

- Cloned the repo as is
- System running Kali 2021.2, Python 3.9.2

It installs correctly with:
- requests v2.25.1
- urllib3 v1.26.5

Still need to check if it breaks something or not, but should likely be ok.

**Comment by Ganapati** [comment]
thx ! fixed
