### ISSUE TITLE
Replace signal with cross-platform alternative

### ISSUE THREAD

**Issue by Reelix** [Ganapati/RsaCtfTool#265]
In lib/utils.py you make use of the `signal` class - Specifically `SIGALARM` and `alarm`

https://github.com/Ganapati/RsaCtfTool/blob/bf3c0148f7ab0592deba702160f502d29ca7dbe1/lib/utils.py#L192-L196

These functions are Unix only, and will break on other platforms (Eg: Windows)

https://docs.python.org/3/library/signal.html#signal.SIGALRM
https://docs.python.org/3/library/signal.html#signal.alarm

**Comment by daedalus** [comment]
I strongly disagree changing a standar API for a non standar posix OS even if it has a majority of the user base (for now).

On the other hand the python signals API has at some degree a compatibility for signals with ms_windows:

`On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, SIGTERM, or SIGBREAK. A ValueError will be raised in any other case. Note that not all systems define the same set of signal names; an AttributeError will be raised if a signal name is not defined as SIG* module level constant.` sic https://docs.python.org/3/library/signal.html

I think it is a matter of time that for the SIGALARM to be implemented on ms_windows.

If anybody "whants" to be a hacker or learn RSA or just hack things for the sake of pleasure then they need to force themselves to use another thing than ms_windows.
