### ISSUE TITLE
Error Crypto.PublicKey

### ISSUE THREAD

**Issue by malwarewonder** [Ganapati/RsaCtfTool#27]
Hello,

I keep getting the following error whenever I try to run the script

```
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 17, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey
```

I've installed all dependencies like asked in the requirements.txt

Thank you,

**Comment by Ganapati** [comment]
is pycrypto correctly installed ?

**Comment by shack2012** [comment]
same issue even with pycrypto installed

**Comment by ivansena35** [comment]
got the same issue, this is the output from pip install -r "requirements.txt":

**Requirement already satisfied: PyCrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.6.1)**
Requirement already satisfied: GMPY2 in /usr/local/lib/python2.7/dist-packages/gmpy2-2.1.0a3.dev0-py2.7-linux-x86_64.egg (from -r requirements.txt (line 2)) (2.1.0a3.dev0)
Requirement already satisfied: SymPy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.18.4)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python2.7/dist-packages (from SymPy->-r requirements.txt (line 3)) (1.0.0)

**Comment by Ganapati** [comment]
Thx ivansena35 !
