### ISSUE TITLE
More than two primes

### ISSUE THREAD

**Issue by mendel3** [Ganapati/RsaCtfTool#270]
This might not be feasible, but support for private keys with more than two primes would be really nice. There are some specific attacks [here](https://link.springer.com/content/pdf/10.1007/3-540-36492-7_25.pdf) and [here](http://cacr.uwaterloo.ca/techreports/2006/cacr2006-16.pdf), and I think many of the sage attacks and siqs would already work. This could be enabled by an argument, so normal two prime searching isn't affected.

**Comment by Ganapati** [comment]
I'd be happy to merge the attack if you make a pull request !
I have no time right now to read and implement this.
