### ISSUE TITLE
Problem with second argument in uncipherfile

### ISSUE THREAD

**Issue by stevendamianakis** [Ganapati/RsaCtfTool#273]
![image](https://user-images.githubusercontent.com/58956168/125874918-62c0cb7b-194a-44ff-8a3f-a5a98f262efb.png)

**Comment by Ganapati** [comment]
uncipherfile is not created to handle multiple values. you can try `./message*.txt` instead

**Comment by stevendamianakis** [comment]
![image](https://user-images.githubusercontent.com/58956168/126514604-194c031b-07b9-4426-8446-dcc64fbcfda9.png)
