### ISSUE TITLE
False positive when lib/nsif/nsifc is missing

### ISSUE THREAD

**Issue by SynacktivCerv** [Ganapati/RsaCtfTool#278]
Trying an attack without having the file _lib/nsif/nsifc_ installed returned this:

```
[*] Performing nsif attack on /tmp/tmptkcgwroj.
sh: lib/nsif/nsifc: not found
[*] Attack success with nsif method !
```

The script _attacks/single_key/nsif.py_ must check if the file exists.

**Comment by Ganapati** [comment]
I've checked NSIF attack and there is too much work for now.
I've temporary deactivated the module.
