### ISSUE TITLE
No output of private key

### ISSUE THREAD

**Issue by tobecwb** [Ganapati/RsaCtfTool#28]
Used the following command:

`RsaCtfTool.py --publickey public.key --private`

After some minutes (2 or 3), the RsaCtfTool ends, with no output.
No errors, no information, no new files... nothing.

**Comment by Ganapati** [comment]
Fixed !

/m/v/t/c/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py --publickey /tmp/test.pub --private
[-] Sorry, cracking failed
