### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by wcc526** [Ganapati/RsaCtfTool#281]
#9 2689.2     /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: error: lto-wrapper failed
#9 2689.2     collect2: error: ld returned 1 exit status
#9 2689.2     make[2]: *** [src/shell/CMakeFiles/shell.dir/build.make:1822: z3] Error 1
#9 2689.2     make[1]: *** [CMakeFiles/Makefile2:4491: src/shell/CMakeFiles/shell.dir/all] Error 2
#9 2689.2     make[1]: *** Waiting for unfinished jobs....
#9 2689.2     [ 98%] Built target libz3
#9 2689.2     make: *** [Makefile:136: all] Error 2
#9 2689.2     error: Unable to build Z3.
#9 2689.2     ----------------------------------------
#9 2689.7 ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-elqiuybm/z3-solver_b7ae5f0f2e1f48c59afc7987154c1b71/setup.py'"'"'; __file__='"'"'/tmp/pip-install-elqiuybm/z3-solver_b7ae5f0f2e1f48c59afc7987154c1b71/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wrm3ez_7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/z3-solver Check the logs for full command output.
------

**Comment by Ganapati** [comment]
Latest commit change the docker file, can you try it ?
Sorry but I suck at docker so i rely on pull request for this...

**Comment by daedalus** [comment]
This is an upstream bug in alpine linux.

https://github.com/openethereum/openethereum/issues/230
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396

I'm trying to figureout a workarround.

**Comment by Ganapati** [comment]
Known issue, working on it (sort of...)
