### ISSUE TITLE
a little bug

### ISSUE THREAD

**Issue by Nixiabing** [Ganapati/RsaCtfTool#287]
n = 2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601

e = 58134567416061346246424950552806959952164141873988197038339318172373514096258823300468791726051378264715940131129676561677588167620420173326653609778206847514019727947838555201787320799426605222230914672691109516799571428125187628867529996213312357571123877040878478311539048041218856094075106182505973331343540958942283689866478426396304208219428741602335233702611371265705949787097256178588070830596507292566654989658768800621743910199053418976671932555647943277486556407963532026611905155927444039372549162858720397597240249353233285982136361681173207583516599418613398071006829129512801831381836656333723750840780538831405624097443916290334296178873601780814920445215584052641885068719189673672829046322594471259980936592601952663772403134088200800288081609498310963150240614179242069838645027877593821748402909503021034768609296854733774416318828225610461884703369969948788082261611019699410587591866516317251057371710851269512597271573573054094547368524415495010346641070440768673619729280827372954003276250541274122907588219152496998450489865181536173702554116251973661212376735405818115479880334020160352217975358655472929210184877839964775337545502851880977049299029101466287659419446724781305689536816523774995178046989696610897508786776845460908137698543091418571263630383061605011820139755322231913029643701770497299157169690586232187419462594477116374977216427311975598620616618808494138669546120288334682865354702356192972496556372279363023366842805886601834278434406709218165445335977049796015123909789363819484954615665668979
![1628080905423](https://user-images.githubusercontent.com/20591728/128182518-b702422c-bd1e-4ec7-92e3-93fdaa6da7f1.jpg)

**Comment by Ganapati** [comment]
Hi !
Where did you values come from ? a challenge ? a valid rsa key ?

**Comment by Ganapati** [comment]
The only fix I found was patching `pycryptodome` and change construct default `consistency_check` arg to `False`... Sorry

**Comment by daedalus** [comment]
This is not a bug in the tool but a feature in the underlying pycryptodome lib.

Is spected that a perfect square is a case where the factorization is trivial therefore rendering such RSA key useless. Beacuse N=PQ and P=Q.

The function pre_attack_check in lib/rsa_attack.py was intended to catch those cases.
