### ISSUE TITLE
Dependencies conflict causing ImportError: cannot import name 'DerBitString'

### ISSUE THREAD

**Issue by Boneill3** [Ganapati/RsaCtfTool#289]
tested on python versions 3.9.4 and 3.9.6 pip 21.1.3
only installed "requirements.txt"

❯ ./RsaCtfTool.py -h
Traceback (most recent call last):
  File "/Users/.../Documents/CTF/RsaCtfTool/./RsaCtfTool.py", line 19, in <module>
    from Crypto.PublicKey import RSA
  File "/Users/..../.pyenv/versions/3.9.6/lib/python3.9/site-packages/Crypto/PublicKey/__init__.py", line 21, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
ImportError: cannot import name 'DerBitString' from 'Crypto.Util.asn1' (/Users/.../.pyenv/versions/3.9.6/lib/python3.9/site-packages/Crypto/Util/asn1.py)

## Workaround from https://github.com/matlink/gplaycli/issues/147
pip uninstall PyCrypto
pip uninstall PyCryptodome
pip install PyCryptodome

**Comment by Ganapati** [comment]
Your fix is the good one : 
```pip uninstall PyCrypto
pip uninstall PyCryptodome
pip install PyCryptodome```

**Comment by datu12** [comment]
Hey all I tried those walk ways, however im still getting this error
  ```
File "/home/kali/Desktop/htb/begginer_track/RsaCtfTool.py", line 19, in <module>
    from lib.crypto_wrapper import RSA
ModuleNotFoundError: No module named 'lib'

**Comment by daedalus** [comment]
did you clone the repo? how did you get it?
