### ISSUE TITLE
PyCrypto, gmpy, gmpy2 packages do not install

### ISSUE THREAD

**Issue by Millwr1ght** [Ganapati/RsaCtfTool#294]
I tried and failed to install RsaCtfTool today, (windows 10, Python 3.8.9, cloned repo as is)

After looking through and deciphering error messages, I have found a few things:
 - gmpy, gmpy2, and pycrypto fail to install
 - pycrypto fails because inttypes.h in C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\ has an error ([issue #284 from pycrypto](https://github.com/pycrypto/pycrypto/issues/284))
 - gmpy and gmpy2 fail because the wheel builder can't find a gmp.h file
 - installing these packages manually doesn't work for the same reasons

Possible solutions
 - installing the most recent version of gmpy2 works: 'pip install gmpy2==2.1.0rc1'
 - from [issue #284 from pycrypto](https://github.com/pycrypto/pycrypto/issues/284): [this blog post](http://www.xavierdupre.fr/app/pymyinstall/helpsphinx/blog/2017/2017-01-03_pycrypto.html) has an explanation of how to fix inttypes.h so pycrypto can install (leastways on windows)
 - no idea if these break anything, can't find a way to get gmpy nicely

**Comment by krishyadav007** [comment]
Same issue here on Ubuntu 20.04

**Comment by krishyadav007** [comment]
Solution

Install
```
sudo apt-get install libgmp3-dev libmpc-dev
```
And then try installing
