### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rarpunzel** [Ganapati/RsaCtfTool#297]
Hello, I tried to use the tool for solving one of the machines in HTB, I try to follow some writeups and most of the writeups don't have issues as I did. Here is the error I found, I tried to search for the solution but I can't find it :(

root@kali ~Documents/HTB/***: python ~/Documents/tools/RsaCtfTool/RsaCtfTool.py --publickey rootauthorizedsshkey.pub --private > id_rsa
Traceback (most recent call last):
  File "/root/Documents/tools/RsaCtfTool/RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/root/Documents/tools/RsaCtfTool/lib/rsa_attack.py", line 243
    f"[*] Attack success with {attack_module.get_name()} method !"
                                                                 ^
SyntaxError: invalid syntax

**Comment by Ganapati** [comment]
I think your are using python in version < 3.6.
