### ISSUE TITLE
Information about each attack

### ISSUE THREAD

**Issue by Pola8976** [Ganapati/RsaCtfTool#298]
It would be great if you could provide a little description about each attack, and a link to a source with in-depth info. I am unable to find information on some like 'noveltyprimes'.

**Comment by shinmai** [comment]
I know this issue is old, but for many/most of the attacks if you check the impelementations in the /[attacks](https://github.com/Ganapati/RsaCtfTool/tree/master/attacks)/ folder, many of them have informative comments, like the aforementioned 'noveltyprimes':

> primes" of the form 31337 - 313333337 - see ekoparty 2015 "rsa 2070" not all numbers in this form are prime but some are (25 digit is prime)
