### ISSUE TITLE
Docker image no longer available

### ISSUE THREAD

**Issue by KamilPacanek** [Ganapati/RsaCtfTool#301]
Hey,
I don't know if that was you who pulled the Docker image down, but it is no longer available in the Docker Hub despite the fact it is listed as one of the usage examples here on GitHub.

![image](https://user-images.githubusercontent.com/20944885/144318692-2678155d-94bd-4157-9e2f-73f788da3404.png)

**Comment by Ganapati** [comment]
It's no me who created/pushed the docker image nor me who put it down, so I have no information about this, sorry !

**Comment by KamilPacanek** [comment]
That's ok, thanks!
