### ISSUE TITLE
attack module not implemented yet

### ISSUE THREAD

**Issue by arsyadbruh** [Ganapati/RsaCtfTool#303]
while again try attack nsif show warning **this attack module is not implemented yet** . I don't know if there is any configuration I should do or a command to type

![image](https://user-images.githubusercontent.com/71438511/147499221-431373de-c047-43ad-9755-0f065c38a38a.png)

**Comment by daedalus** [comment]
NSIF code sould be cleaned up, the core of the attack lives in https://github.com/Ganapati/RsaCtfTool/blob/master/lib/nsif/nsif.py but it is up to @Ganapati since is his project.

**Comment by daedalus** [comment]
I found out that all that the NSIF code does its just computing primes >= 3^n [OEIS A104081](https://oeis.org/A104081).
```
from gmpy2 import *

a = next_prime(3**129)
b = next_prime(3**131)
n = a*b
print(a,b,n)

def factor(n, base=3):
  """
  A104081:  Smallest prime >= 3^n.
  """
  power = 1
  while True:
    p = next_prime(base ** power)
    if n % p == 0:
      return p, n // p
    power += 1

print(factor(n))
```

**Comment by Ganapati** [comment]
> NSIF code sould be cleaned up, the core of the attack lives in https://github.com/Ganapati/RsaCtfTool/blob/master/lib/nsif/nsif.py but it is up to @Ganapati since is his project.

yep, but no time to do this... sorry !
