### ISSUE TITLE
Switches don't work with full path of files

### ISSUE THREAD

**Issue by C9ECL1PSE** [Ganapati/RsaCtfTool#310]
Hey I noticed that the tool doesn't work when using full paths as arguments. It doesn't display output for a successful crack.  

However, if the key and file are in the same path as the tool itself, then it will work fine.

See pasted image. 

![rsa-ctf-tool-full-path-issue](https://user-images.githubusercontent.com/68455819/159797720-4b51e299-23e2-4ee0-89c7-ad3b343482c9.PNG)

**Comment by Ganapati** [comment]
you didn't provide the `--private` argument in your example, so no private key will be displayed.
