### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by Conrad-Push** [Ganapati/RsaCtfTool#311]
ModuleNotFoundError: No module named 'Crypto'

I have this issue during every command I've typed ://

**Comment by Conrad-Push** [comment]
Ok, I've found a solution in README :D

**Comment by LenceOfTheOrder** [comment]
Hello, @Conrad-Push, I'm having the same issue you described. Would you mind explaining the solution? I wasn't able to find it...
