### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by harshafriend4alll** [Ganapati/RsaCtfTool#32]
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 658, in <module>
    attackobj.attack()
  File "./RsaCtfTool.py", line 478, in attack
    getattr(self, attack.__name__)()
  File "./RsaCtfTool.py", line 410, in siqs
    if siqsobj.checkyafu() and siqsobj.testyafu():
  File "/root/Desktop/ctf/tools/RsaCtfTool/siqs.py", line 39, in testyafu
    if b'48670331' in yafutest:
TypeError: 'in <string>' requires string as left operand, not bytes

publickey 
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIVCe6WrpgUA5ogDr69OKuJSPQ06ICDP
2LbsOZcE6YdET6rixTHqko3sI8Y91us1ZKSsLUerv3NK9Qr8C26IbRcCAwEAAQ==
-----END PUBLIC KEY-----

**Comment by Ganapati** [comment]
No problem on the last version (on my computer) with your pubkey.
Are you using Python3 (project fully moved to Python3) ?

`/m/v/t/c/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py --publickey /tmp/test.pub --private --verbose
[...]

[*] Yafu SIQS is working.

[-] Modulus too big for SIQS method.

[...]`

**Comment by Ganapati** [comment]
Ok, bug found and fixed.
Thanks for the report !
