### ISSUE TITLE
Unable to install requirements.txt GMPY2 error

### ISSUE THREAD

**Issue by JaySee95** [Ganapati/RsaCtfTool#329]
× Running setup.py install for gmpy2 did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/gmpy2
      copying gmpy2/__init__.py -> build/lib.linux-x86_64-3.10/gmpy2
      running egg_info
      writing gmpy2.egg-info/PKG-INFO
      writing dependency_links to gmpy2.egg-info/dependency_links.txt
      writing top-level names to gmpy2.egg-info/top_level.txt
      reading manifest file 'gmpy2.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'COPYING'
      adding license file 'COPYING.LESSER'
      writing manifest file 'gmpy2.egg-info/SOURCES.txt'
      copying gmpy2/__init__.pxd -> build/lib.linux-x86_64-3.10/gmpy2
      copying gmpy2/gmpy2.h -> build/lib.linux-x86_64-3.10/gmpy2
      copying gmpy2/gmpy2.pxd -> build/lib.linux-x86_64-3.10/gmpy2
      running build_ext
      building 'gmpy2.gmpy2' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/src
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./src -I/usr/include/python3.10 -c src/gmpy2.c -o build/temp.linux-x86_64-3.10/src/gmpy2.o -DSHARED=1
      In file included from src/gmpy2.c:461:
      src/gmpy2.h:446: warning: "Py_RETURN_NOTIMPLEMENTED" redefined
        446 | #define Py_RETURN_NOTIMPLEMENTED \
            |
      In file included from /usr/include/python3.10/Python.h:74,
                       from src/gmpy2.c:445:
      /usr/include/python3.10/object.h:623: note: this is the location of the previous definition
        623 | #define Py_RETURN_NOTIMPLEMENTED return Py_NewRef(Py_NotImplemented)
            |
      In file included from src/gmpy2.c:593:
      src/gmpy2_hash.c: In function ‘_mpfr_hash’:
      src/gmpy2_hash.c:150:20: error: ‘_PyHASH_NAN’ undeclared (first use in this function); did you mean ‘Py_IS_NAN’?
        150 |             return _PyHASH_NAN;
            |                    ^~~~~~~~~~~
            |                    Py_IS_NAN
      src/gmpy2_hash.c:150:20: note: each undeclared identifier is reported only once for each function it appears in
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Receive this error when installing requirements.txt

**Comment by m0d1cumc0rvu5** [comment]
sudo apt install python3-venv
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install gmpy2
Then remove gmpy2 from your local requirements.txt file
pip3 install -r "requirements.txt"
Should do the trick

**Comment by nephi-duff** [comment]
`sudo apt install libmpc-dev` and `pip install -r requirements.txt` worked for me. `z3-solver` is going to take a while to build after that so be patient.

**Comment by JaySee95** [comment]
Thank you! @m0d1cumc0rvu5 suggestion worked!
