### ISSUE TITLE
how creat public key from  n & e format base64 ?

### ISSUE THREAD

**Issue by cbogithub** [Ganapati/RsaCtfTool#4]
example. 
n="omXjOQmHl77TtpwMXL9WPcd+Xcg1bh8CoLGOyX1Ug/CLtZJx/SvSo0bj5bEiVb8eCa5mXuc6sDg9/RRpCvKHHxZG6f9qh5r3ZNY+yr5hKQqeMafWa4b6UqouLSSwKsNe5FWD327BoyaEsMyCRheQg4wX86G/8zqynuvbT6KzQbQtp4iqQvMWGswovmflsk7zoZUESAFu6L5xlJUEFXMlDLPH13SsPKwvL4MgHa+Cx938B0FReUFtq7qEQHIPhGSTOeTS+v8Acp6VqkmcLB4kCIsk/Icr46VTEPv3WWDHcbSzp+RPR0lTa8WTdOd/E98U70jfAZJAKMDWr4sQkvfk7w=="

e= "AQAB"

**Comment by Ganapati** [comment]
Can you explain your needs ? Is this from a ctf or challenge ?
Why don't you use the "classic" method by debase64 before ?

**Comment by Ganapati** [comment]
No response, no fix.
