### ISSUE TITLE
Unknown bug with Kali Linux

### ISSUE THREAD

**Issue by geniusKoder** [Ganapati/RsaCtfTool#44]
Hi your tools are great. But recently, I encountered a bug, whereby my teammate can use factordb attack to break one of the RSA, but I am unable to do so with the exact same numbers. We both ran it in auto mode, however his breaks the RSA and mine dosen't. We are using 2 different versions of Kali Linux with mine being the latest and his slightly older. Thanks. I am not too sure if I can provide the test case yet as it may not be ready for release yet.

This is mine:
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

**Comment by dinaelhanan** [comment]
Are you getting no output or what output are you getting?

**Comment by geniusKoder** [comment]
There is no output

**Comment by geniusKoder** [comment]
I mean if it is with verbose I can see it running through the different attacks, but there is no output at the end.

**Comment by dinaelhanan** [comment]
I'm on a work computer right now but I'll try running it on my laptop and get back to you

**Comment by geniusKoder** [comment]
Sure. Thanks for update!

**Comment by dinaelhanan** [comment]
Im on ubuntu, it worked for me but it took a long time. I got the plaintext (a picoCTF flag) which I wont post. Try running it with sudo. If it doesn't work, I'll get back to you when I try running it with my kali linux USB. I'll try to find the bug and figure out what's wrong and submit a pull request.

**Comment by geniusKoder** [comment]
root@kali:~/RsaCtfTool# python RsaCtfTool.py -n 19873983286782560325097231669062231706101975263854986576179713866230024081799427 -e 65537 --uncipher 6016191969250499616074780740520031717318605913396082232575066605397958585882117 --verbose --attack all
[*] Performing hastads attack.
[*] Performing factordb attack.
[*] Performing pastctfprimes attack.
[*] Loaded 71 primes
[*] Performing mersenne_primes attack.
[*] Performing noveltyprimes attack.
[*] Performing smallq attack.
[*] Performing wiener attack.
[*] Performing comfact_cn attack.
[*] Performing primefac attack.
[*] Performing fermat attack.
[*] Performing siqs attack.
[*] Yafu SIQS is not working.
[*] Performing Pollard_p_1 attack.

That's all the output I got. Hope to hear your update soon. :)

**Comment by dinaelhanan** [comment]
Thanks for your patience, I know I've been putting this off! I tried it with kali and it wouldn't even start. Then, I relalized I have to do the Ubuntu/Kali specific instructions (check it out here: https://github.com/Ganapati/RsaCtfTool/pull/43/files or in the README file) . If you've done that, just let me know and I'll look into it further. I went over the code and nothing seems to be wrong. I will look into that one bit though that says:
"[] Yafu SIQS is not working."
Which I think is the issue.

**Comment by Ganapati** [comment]
Fixed in last commit : 

FactorDb use an expired certificate for https.
RsaCtftool no longer check validity...

Result :

/m/v/p/RsaCtfTool ❯❯❯ python3 RsaCtfTool.py -n 19873983286782560325097231669062231706101975263854986576179713866230024081799427 -e 65537 --uncipher 6016191969250499616074780740520031717318605913396082232575066605397958585882117 --verbose
[*] Performing hastads attack.
[*] Performing factordb attack.
[+] Clear text : b'\x00\x00picoCTF{us3_l@rg3r_pr1m3$_1850}'

**Comment by geniusKoder** [comment]
Great! Thanks for fixing it. Maybe I didn't do enough testing but apparently if I download the tool from ZIP it works but if I do gitclone it dosen't.
You can see from below that running the tool from the ZIP file which I placed in my desktop worked but not the one from gitclone, which I had already deleted and tried to install. Not that big an issue, probably not a bug on your side but just to let you know. Cheers! :)

root@kali:~/Desktop/RsaCtfTool-master# python RsaCtfTool.py -n 19873983286782560325097231669062231706101975263854986576179713866230024081799427 -e 65537 --uncipher 6016191969250499616074780740520031717318605913396082232575066605397958585882117 --verbose --attack all
[*] Performing hastads attack.
[*] Performing factordb attack.
[+] Clear text : picoCTF{us3_l@rg3r_pr1m3$_1850}
root@kali:~/Desktop/RsaCtfTool-master# ls
boneh_durfee.sage  examples   optional-requirements.txt  partial_q.py       _primefac    README.md         RsaCtfTool.py  rsalibnum.pyc  smallfraction.sage  wiener_attack.py
ecm.sage           fermat.py  p_1.py                     pastctfprimes.txt  primefac.py  requirements.txt  rsalibnum.py   siqs.py        test.sh             yafu
root@kali:~/Desktop/RsaCtfTool-master# cd ..
root@kali:~/Desktop# cd ..
root@kali:~# ls
Desktop  Documents  Downloads  Music  Pictures  Public  RsaCtfTool  Templates  Videos
root@kali:~# cd RsaCtfTools
bash: cd: RsaCtfTools: No such file or directory
root@kali:~# cd RsaCtfTool
root@kali:~/RsaCtfTool# python RsaCtfTool.py -n 19873983286782560325097231669062231706101975263854986576179713866230024081799427 -e 65537 --uncipher 6016191969250499616074780740520031717318605913396082232575066605397958585882117 --verbose --attack all
[*] Performing hastads attack.
[*] Performing factordb attack.
[*] Performing pastctfprimes attack.
[*] Loaded 71 primes
[*] Performing mersenne_primes attack.

**Comment by geniusKoder** [comment]
Ok cool. It works now on the pulled version too. Thanks for fixing the bug once again! :)
