### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by juniorhero** [Ganapati/RsaCtfTool#45]
Getting error

python3 ./RsaCtfTool.py --publickey tmp1 --uncipher tmp5 --verbose
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 653, in <module>
    args.uncipher = int(args.uncipher)
ValueError: invalid literal for int() with base 10: 'tmp5'

tmp1

MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhALxHhYGPVMYmx3vzJbPPAEa10NETXrV3
mI9wJizmFJhrAgMBAAE=

tmp5
mTJPrVNiiaHi0Y3QImXNfxVXnWecid0ZVMjFbzeNEUk=

also tried this as uncipher file
bVRKUHJWTmlpYUhpMFkzUUltWE5meFZYbldlY2lkMFpWTWpGYnplTkVVaz0K

need help

**Comment by juniorhero** [comment]
I am trying to get  Get cleartext from cipher and pubkey

**Comment by juniorhero** [comment]
also used this as cipher 2O­Sb¡âÑÐ"eÍWgÝTÈÅo7I   still didnt work

**Comment by dinaelhanan** [comment]
I think the equal sign is freaking it out. (that's why it says "ValueError: invalid literal for int() with base 10: 'tmp5'") Convert tmp1 and tmp5 from base64 to decimal and try that.

Also, have you tried using:
Python2.7 RsaCtfTool.py 
(I get errors when using python3 when I tried to replicate this)

If my advice doesn't make sense or is incorrect, please let me know. I'm just starting out on github but I've used this tool for picoCTF so I've had some experience on it. Hope this helps.

**Comment by dinaelhanan** [comment]
Also, can I get this issue assigned to me? Looks like a good first issue. Hopefully I can help out and resolve it!

**Comment by Ganapati** [comment]
Hi, I can't assign this issue to you, but you can fork and make a pull request if you patch it !

**Comment by Ganapati** [comment]
Did you try uncipher-file ?

**Comment by dinaelhanan** [comment]
I don't think that's it needs patching, if it ends up being a bug I'll help out but I think if @juniorhero tries my suggestions it may help.

**Comment by Ganapati** [comment]
Solution : 
Write the b64 key in file like this (/tmp/test.pub in my case):
-----BEGIN PUBLIC KEY-----
MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhALxHhYGPVMYmx3vzJbPPAEa10NETXrV3
mI9wJizmFJhrAgMBAAE=
-----END PUBLIC KEY-----

Then, you have to use --uncipherfile tmp5 and not --uncipher tmp5

results :
/m/v/p/RsaCtfTool ❯❯❯ python3 ./RsaCtfTool.py --publickey /tmp/test.pub --verbose --uncipherfile /tmp/tmp5
[*] Performing hastads attack.
[*] Performing factordb attack.
[+] Clear text : b'\x00\x02\x11\x96\xa91\xfb\x13\xd46\xba\x00nevermindthebollocks'

**Comment by juniorhero** [comment]
Thanks for the solution will try out soon
