### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by noraj** [Ganapati/RsaCtfTool#50]
add a license

https://tldrlegal.com/

https://choosealicense.com/

**Comment by dinaelhanan** [comment]
Will work on this too :)

**Comment by Ganapati** [comment]
License is already in the rsactftool.py file :

----------------------------------------------------------------------------
"THE BEER-WARE LICENSE" (Revision 42):
ganapati (@G4N4P4T1) wrote this file. As long as you retain this notice you
can do whatever you want with this stuff. If we meet some day, and you think
this stuff is worth it, you can buy me a beer in return.
----------------------------------------------------------------------------

**Comment by noraj** [comment]
@Ganapati Create a LICENSE file too please.

**Comment by dinaelhanan** [comment]
#52 @noraj there you go :)
