### ISSUE TITLE
[Discussion] N was a 2048 bit prime

### ISSUE THREAD

**Issue by s0h3ck** [Ganapati/RsaCtfTool#53]
You mentioned at the end of the README.md file.

> Saw a CTF where the supplied N was a 2048 bit prime. Detect this and solve using phi = (n - 1) * (n - 1) which seemed to work for that CTF

1. Can you link me the name of the challenge and the competition name?

2. What is the principle used in this trick `phi = (n - 1) * (n - 1)` ? Any technical paper I can read on?

> phi(n) = phi(pq) = (p - 1)(q - 1) = pq - p  - q + 1 = n - p - q + 1 = n - (p + q) + 1
> phi(n) = (n - 1)
> phi(n²) = (n - 1)n^(2 - 1) = n² - n

> phi(mn) = phi(m)phi(n) if m and n are coprime integers.

3. Would it be because p - 1 is a multiplication of low prime numbers?

If that is the case, then probably Pollard's p − 1 algorithm was used during the CTF you saw.

**Comment by Ganapati** [comment]
This part of readme was written by sourcekris. no idea sorry.
