### ISSUE TITLE
Find d when n is prime

### ISSUE THREAD

**Issue by jokker87** [Ganapati/RsaCtfTool#54]
We encountered a ctf challenge, where n was prime and tried to solve it with RsaCtfTool.

Attached to the issue is our java code, the public key and the secret. Would be cool if you could add this to the tool.

[SolveDwhenNisPrime.zip](https://github.com/Ganapati/RsaCtfTool/files/2719515/SolveDwhenNisPrime.zip)

**Comment by dinaelhanan** [comment]
I encountered the same one from a CTF! Hope they add it. Wouldcheck it out myself too, but I'm bogged down with exams rn :/

**Comment by jokker87** [comment]
I will take a look at the python code and maybe do a pull request. Guess shouldn't be too hard to implement it.

**Comment by nloding** [comment]
I'd love to see the Python implementation of this. I tried but was doing something wrong with the actual deciphering of the ciphertext. I know my math for d was correct. I'm not a Python dev, so I'm sure I did something horribly wrong. Would love to see the PR if you create one!

**Comment by jokker87** [comment]
Added #56, check it out and hopefully it will get accepted.

happy new year ;)

**Comment by Ganapati** [comment]
Thanks to jokker87, this feature is now on the master branch !
