### ISSUE TITLE
Factoring fails when primes are not close enough

### ISSUE THREAD

**Issue by jam3swong** [Ganapati/RsaCtfTool#59]
I am trying to factor 

```
n = 316341779932648675985791704990724089516454422587094833169408333523414739834909517309715699939317715087526517454431375116879351671364301319495659096020992713723208722190937740766450883017917635799026613109992174843186393756297174271962473795425087410844561019652906553118852648659911340204749198564105889477617
``` 

but the tool fails for this number (I guess the difference |p-q| is too large). The two primes are

```
p = 17785999548314642751774703489649490792859797093721105132562728724448911505635166813224212967627398814715202394464187693886191289350137588089220151890768019
q = 17785999548314642751774703489649490792859797093721105132562728724448915173277940491632723963037561789695844144194444626441506989745893161735904252626571243
```

I found this paper, which seems to improve the Fermat factorization https://hsbp.org/tiki-download_wiki_attachment.php?attId=174

Would you consider adding something like this?

Cheers,
James

**Comment by jam3swong** [comment]
@Sjord: Yeah, I tried that as well. It might be possible to go a bit higher by guessing bits.

I found a [blogpost](https://grocid.net/2017/09/16/finding-close-prime-factorizations/), which proposes an algorithm that solves the problem for this instance. By setting the `b` parameter slightly higher than in the blogpost, it worked!

```
def close_factor(n, b):
 
    # approximate phi
    phi_approx = n - 2 * gmpy.sqrt(n) + 1
 
    # create a look-up table
    look_up = {}
    z = 1
    for i in range(0, b + 1):
        look_up[z] = i
        z = (z * 2) % n
 
    # check the table
    mu = gmpy.invert(pow(2, phi_approx, n), n)
    fac = pow(2, b, n)
    j = 0
 
    while True:
        mu = (mu * fac) % n
        j += b
        if mu in look_up:
            phi = phi_approx + (look_up[mu] - j)
            break
        if j > b * b:
            return
 
    m = n - phi + 1
    roots = (m - gmpy.sqrt(m ** 2 - 4 * n)) / 2, \
            (m + gmpy.sqrt(m ** 2 - 4 * n)) / 2
 
    return roots
 
n = 316341779932648675985791704990724089516454422587094833169408333523414739834909517309715699939317715087526517454431375116879351671364301319495659096020992713723208722190937740766450883017917635799026613109992174843186393756297174271962473795425087410844561019652906553118852648659911340204749198564105889477617
b = 20000000
 
close_factor(n, b)
```

This returns

```
(mpz(17785999548314642751774703489649490792859797093721105132562728724448911505635166813224212967627398814715202394464187693886191289350137588089220151890768019L), mpz(17785999548314642751774703489649490792859797093721105132562728724448915173277940491632723963037561789695844144194444626441506989745893161735904252626571243L))
[Finished in 39.6s]```

Could be interesting to add this to the tool maybe?

**Comment by Sjord** [comment]
I [made some changes](https://github.com/Sjord/londahl-close-factoring/blob/master/factor.py) to make this compatible with Python 3 and GMPY2.

**Comment by jam3swong** [comment]
Looks good. Can we create a pull request for this?

**Comment by Sjord** [comment]
@Ganapati Any thoughts on this? Would this completely replace the Fermat module? What is a good value for _b_?

**Comment by Ganapati** [comment]
> Looks good. Can we create a pull request for this?

Yep ! Good work :)

**Comment by jam3swong** [comment]
> @Ganapati Any thoughts on this? Would this completely replace the Fermat module? What is a good value for _b_?

Can _b_ be a CLI parameter? Suppose that a good default value for _b_ depends on which order the attacks are run?

**Comment by Ganapati** [comment]
we could set b to 20000000 and make it an optional argument no?
