### ISSUE TITLE
create pub key

### ISSUE THREAD

**Issue by su314ka** [Ganapati/RsaCtfTool#61]
Hi,

I receive the below error when I try to create a bub key. What I`m doing wrong?
Thanks!

python2.7 ./RsaCtfTool.py --createpub -n 046bd20f8fe764c28f5fe1c4eba69d26e0af42bf1853213d593a5098e075344d6fdc998e9c1e469cad7d799a0891f3bc47ae1f6a1eb6caabd62890a7994f4b6d5f -e 65537
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 679, in <module>
    args.n = int(args.n)
ValueError: invalid literal for long() with base 10: '046bd20f8fe764c28f5fe1c4eba69d26e0af42bf1853213d593a5098e075344d6fdc998e9c1e469cad7d799a0891f3bc47ae1f6a1eb6caabd62890a7994f4b6d5f'

**Comment by Sjord** [comment]
The problem is that RsaCtfTool interprets the modulus as a base 10 number, whereas you provide it as hexadecimal. Try prefixing it with `0x` to indicate that it is a hex value:

    RsaCtfTool.py --createpub -n 0x046bd20f8fe764c28f...

**Comment by boworkgo** [comment]
```
python RsaCtfTool.py --uncipher 7022848098469230958320047471938217952907600532361296142412318653611729265921488278588086423574875352[32/43]
765943911598056510802236985767089349939516184644601094223773299727378760601679038576137632949323266192662817259004974274580478619731530125065
95691389361443123047595975834017549312356282859235890330349 --publickey public.key
[!] Warning: primefac attack module missing
Traceback (most recent call last):
  File "RsaCtfTool.py", line 807, in <module>
    attackobj.attack()
  File "RsaCtfTool.py", line 602, in attack
    getattr(self, attack.__name__)()
  File "RsaCtfTool.py", line 424, in londahl
    factors = londahl.close_factor(self.pub_key.n, londahl_b)
  File "/home/bowork/Desktop/RsaCtfTool/londahl.py", line 12, in close_factor
    look_up[z] = i
MemoryError
```

I get a Memory Error when trying to crack an RSA ciphertext.

```
cat public.key
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFwUyakFGGdM3suv1F46d54wIp6L
Huk3va2XRn8tl+WNMyD5A3ONCTivs7LgdtAdXZ8LmfXslCfVlK01zZHzsqzdLGfr
pJ6qVubiBPGWmfPZ0YOs8vbAh0/sibOlvebaHY7wVvKF5l2igmUgJ3VEih/QNAZM
EKBYMHiIPdLXXur1AgMBAAE=
-----END PUBLIC KEY-----
```

And I used this to create the public key
`
python RsaCtfTool.py --createpub -n 64661619081566980804190100354926277870654153140456125893362948358616871347387602985767249018081090677122881379260804173643249531756962204727510922839492155437995895841992167230056775155693770862949166788493903028640851926422098808715056724371516182984131462833172570662800858803285852455362173089675686636277 -e 65537`
