### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by boworkgo** [Ganapati/RsaCtfTool#70]
```
python RsaCtfTool.py --uncipher 7022848098469230958320047471938217952907600532361296142412318653611729265921488278588086423574875352[32/43]
765943911598056510802236985767089349939516184644601094223773299727378760601679038576137632949323266192662817259004974274580478619731530125065
95691389361443123047595975834017549312356282859235890330349 --publickey public.key
[!] Warning: primefac attack module missing
Traceback (most recent call last):
  File "RsaCtfTool.py", line 807, in <module>
    attackobj.attack()
  File "RsaCtfTool.py", line 602, in attack
    getattr(self, attack.__name__)()
  File "RsaCtfTool.py", line 424, in londahl
    factors = londahl.close_factor(self.pub_key.n, londahl_b)
  File "/home/bowork/Desktop/RsaCtfTool/londahl.py", line 12, in close_factor
    look_up[z] = i
MemoryError
```

I get a Memory Error when trying to crack an RSA ciphertext.

```
cat public.key
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFwUyakFGGdM3suv1F46d54wIp6L
Huk3va2XRn8tl+WNMyD5A3ONCTivs7LgdtAdXZ8LmfXslCfVlK01zZHzsqzdLGfr
pJ6qVubiBPGWmfPZ0YOs8vbAh0/sibOlvebaHY7wVvKF5l2igmUgJ3VEih/QNAZM
EKBYMHiIPdLXXur1AgMBAAE=
-----END PUBLIC KEY-----
```

And I used this to create the public key
`
python RsaCtfTool.py --createpub -n 64661619081566980804190100354926277870654153140456125893362948358616871347387602985767249018081090677122881379260804173643249531756962204727510922839492155437995895841992167230056775155693770862949166788493903028640851926422098808715056724371516182984131462833172570662800858803285852455362173089675686636277 -e 65537`

**Comment by Sjord** [comment]
Thank you for your bug report.

The first step of the Löndahl method of factoring builds a big lookup table (20000000 items). It seems that your system does not have free memory to keep this table in memory. On my system, it takes approximately 5 GB of memory, which is definitely much and can't be assumed to be in every system.

I am not sure how to solve this. Maybe we can reduce the memory usage by using another data structure. Also, we could continue the attack with an incomplete lookup table if a memoryerror occurs.

**Comment by Sjord** [comment]
A possible solution is to use Pollard's kangaroo algorithm instead of baby-step-giant-step, as noted in [Löndahl's blog post](https://grocid.net/2017/09/16/finding-close-prime-factorizations/):

> We now do a BSGS-type of algorithm (as noted by hellman in the comments, we can use Pollard’s kangaroo algorithm to avoid exhausting precious memory without sacrificing computational effort, up to polynomial factors).
