### ISSUE TITLE
Make this RsaCtfTool installable by pip

### ISSUE THREAD

**Issue by sandy9999** [Ganapati/RsaCtfTool#71]

**Comment by Ganapati** [comment]
Good idea but i've never pushed a line of code on pip.
I'll check this later.

**Comment by dinaelhanan** [comment]
I'm going to try this out using the article below:
https://dzone.com/articles/executable-package-pip-install

**Comment by nightwatchcyber** [comment]
@Ganapati @dinaelhanan I am providing a pull request for your review with PIP support: see https://github.com/Ganapati/RsaCtfTool/pull/83

**Comment by Ganapati** [comment]
Due to the massive refactoring, the pull-request is no longer compatible...
I'll try to add this functionality later (i've no idea how to do this)
