### ISSUE TITLE
Support "uncipher(file)" with privatekey specified

### ISSUE THREAD

**Issue by OevreFlataeker** [Ganapati/RsaCtfTool#72]
It would be great, if rsactftool could easily support the decryption of a ciphertext also when you already have the private key generated (and not only the public key).

While this here works:
`./RsaCtfTool.py --publickey "pub?.pem" --uncipher 88389551.....`

this doesn't:

`./RsaCtfTool.py --key priv1.pem --uncipher 883895515......
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 806, in <module>
    attackobj = RSAAttack(args)
  File "./RsaCtfTool.py", line 135, in __init__
    if '*' in args.publickey or '?' in args.publickey:
TypeError: argument of type 'NoneType' is not iterable
`
It seems the cmdline parsing logic just assumes a key needs to be attacked but fails to recognize everything's given to actually do something useful.

**Comment by Ganapati** [comment]
New commit for you, you can now use --key yourprivatekey --uncipher yourcipher.
