### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by guiyomh** [Ganapati/RsaCtfTool#73]
Hi @Ganapati ,
I was given a public key and a prime.txt file. And I was challenged to decrypt a file.
I guess I need to regenerate the private key from the public key and the prime.txt file. But I do not know how to do it.
You seem to master the subject well. Can you help me ?

**Comment by Ganapati** [comment]
i can take a look on irc next week if you want :)

Le sam. 18 mai 2019 à 19:23, Guillaume Camus <notifications@github.com> a
écrit :
