### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by lupier** [Ganapati/RsaCtfTool#85]
Floating point exception when call --uncipherfile mode with previously found key. File to uncipher and pub key found in archive. Any ideas why there are exception ?
[test2.zip](https://github.com/Ganapati/RsaCtfTool/files/3642647/test2.zip)

**Comment by Ganapati** [comment]
no idea... I'll check this later.
Thx for report

**Comment by Ganapati** [comment]
Hi !
I've commit a patch for your case, it add a new functionnality : uncipher data with private key (and password if needed)

just try : 
`python3 ./RsaCtfTool.py --key /tmp/test/test2 --uncipherfile /tmp/test/2.bin`
