### ISSUE TITLE
This tool crashes on Windows 10 due to a temporary file permission denied

### ISSUE THREAD

**Issue by capra314cabra** [Ganapati/RsaCtfTool#88]
On running this tool on Windows 10, it will clash with an error :
```
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\[Username]\\AppData\\Local\\Temp\\tmp9z75tld3'
```
It seems that this tool tried to reopen the temp file.

**Comment by Ganapati** [comment]
Lot of code in RsaCtfTool is system dependant and require unix (like using /dev/null).
You can fix this using "delete=False" in tempfile constructors then "os.unlink(temporary_file.name)", but there will be others bugs due to the rest of the code.

Sorry !

**Comment by capra314cabra** [comment]
Thank you! I decide to run it on WSL.
