### ISSUE TITLE
Display value of q when cracked using smallq attack

### ISSUE THREAD

**Issue by ttepatti** [Ganapati/RsaCtfTool#89]
Hello,

I recently used RsaCtfTool to uncipher text which was vulnerable to a smallq attack, given n and e.

For the work I'm doing, I need to find the small value of q that was used to uncipher the text. Is it possible the q value could be added to the verbose output?

Thanks!

**Comment by Ganapati** [comment]
Hi !
New commit for you today, add --dumpkey to your commandline and the script will dump p, q, e, n, d.

**Comment by ttepatti** [comment]
Thanks for all of your hard work! :tada:
