### ISSUE TITLE
Python3 Pip->Pip3 Install

### ISSUE THREAD

**Issue by unKn0wnUser453** [Ganapati/RsaCtfTool#91]
Ubuntu/Kali Install:
git clone https://github.com/Ganapati/RsaCtfTool.git
cd RsaCtfTool
sudo apt-get install libgmp3-dev libmpc-dev
python3 -m venv .
. bin/activate
pip install -r "requirements.txt"
./RsaCtfTool.py

pip install -r "requirements.txt" should be pip3 install -r requirements.txt

**Comment by RuneBergh** [comment]
https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

I assume this is your issue? 

Try this, in addition to installing other necessary libraries, some are mentioned in the same post.  

For Python 2.x use:

   $ sudo apt-get install python-dev
For Python 2.7 use:

   $ sudo apt-get install libffi-dev
For Python 3.x use:

   $ sudo apt-get install python3-dev
For Python 3.4 use:

   $ sudo apt-get install python3.4-dev
For Python 3.7 use:

   $ sudo apt-get install python3.7-dev

**Comment by Ganapati** [comment]
Changed
