### ISSUE TITLE
Make sage calls compatible with virtual envs

### ISSUE THREAD

**Issue by Chadys** [Ganapati/RsaCtfTool#95]
I'm using RsaCtfTool in a conda env with sage installed, but the script doesn't detect it.
That's because of how the check is done: `subprocess.check_output(['sage', '-v'])` and all other subprocess' calls are not executed in the caller's activated conda env (same thing would happen with any other virtual env tool).
Since sage can be called directly from Python, I propose not to use it with subprocess calls anymore but to directly use imports and function calls, that way the code would be cleaner and anyone would be able to use sage without needing to install it globally.
If you agree with the idea, I could make a pull request.
And thank you for providing us with this great tool :)

**Comment by Ganapati** [comment]
Hi !
I've looked how to call sage directly from python, but it seem difficult with py3...
Can you make an example on an attack (like ecm) so i'll try to add it everywhere it's needed?

**Comment by Ganapati** [comment]
Closing for the moment.
