### ISSUE TITLE
Error with this file "pubkey.pem" (attached) ...

### ISSUE THREAD

**Issue by stopoverandcatchfire** [Ganapati/RsaCtfTool#98]
Hi, with this command :

`./RsaCtfTool.py --publickey "pubkey.pem" --private`

tool fail with error:

[*] Testing key challenge/pubkey.pem.
[*] Performing boneh_durfee attack on challenge/pubkey.pem.
[*] Performing pastctfprimes attack on challenge/pubkey.pem.
[*] Performing wiener attack on challenge/pubkey.pem.
[*] Performing primefac attack on challenge/pubkey.pem.
[*] Performing factordb attack on challenge/pubkey.pem.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 256, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/user/Working/RsaCtfTool/lib/rsa_attack.py", line 179, in attack_single_key
    self, self.publickey, self.cipher
  File "/home/user/Working/RsaCtfTool/attacks/single_key/factordb.py", line 56, in attack
    q_id = ids[2]
IndexError: list index out of range

How resolve ?

[pubkey.zip](https://github.com/Ganapati/RsaCtfTool/files/4491838/pubkey.zip)

**Comment by Ganapati** [comment]
It's due to a parsing error on the factordb page, I fix this asap.

**Comment by Ganapati** [comment]
Bug fixed (sorry, crack fail on my computer !)
